name: Setup Cache

inputs:
  prefix:
    description: "Cache key prefix"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    #
    # Cache
    #
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        # create-symlink: true
        append-timestamp: false
        key: ${{ inputs.prefix }}-${{ runner.os }}-${{ github.sha }}-
        restore-keys: |
          ${{ inputs.prefix }}-${{ runner.os }}-${{ github.sha }}-
          ${{ inputs.prefix }}-${{ runner.os }}-
      if: runner.os == 'macOS' || runner.os == 'Linux'

    - name: Configure ccache path
      run: |
        echo "/usr/lib/ccache" >> $GITHUB_PATH
        echo "/usr/local/opt/ccache/libexec" >> $GITHUB_PATH
        echo "/opt/homebrew/opt/ccache/libexec" >> $GITHUB_PATH
      shell: bash
      if: runner.os == 'macOS' || runner.os == 'Linux'

  # - name: Setup Windows Cache
  #   uses: actions/cache@v4
  #   with:
  #     path: |
  #       **/bin/x64
  #       **/lib/x64
  #       **/msbuild/**/x64
  #       **/include/generated

  #     key: ci-${{ runner.os }}-${{ matrix.config }}-${{ github.sha }}
  #     restore-keys: |
  #       ci-${{ runner.os }}-${{ matrix.config }}-
  #       ci-${{ runner.os }}-
  #   if: inputs.cache && runner.os == 'Windows'
