usr/bin/slice2cpp
usr/share/man/man1/slice2cpp.1

usr/bin/slice2freeze
usr/share/man/man1/slice2freeze.1

usr/include/Freeze
usr/include/Glacier2
usr/include/Ice
usr/include/IceBox
usr/include/IceGrid
usr/include/IcePatch2
usr/include/IceSSL
usr/include/IceStorm
usr/include/IceUtil
usr/include/Slice

usr/lib/*/libFreeze.so
usr/lib/*/libGlacier2.so
usr/lib/*/libIce.so
usr/lib/*/libIceBox.so
usr/lib/*/libIceGrid.so
usr/lib/*/libIcePatch2.so
usr/lib/*/libIceSSL.so
usr/lib/*/libIceStorm.so
usr/lib/*/libIceUtil.so
usr/lib/*/libSlice.so
