usr/lib/Ice.min.js usr/share/javascript/ice-@mmver@/
usr/lib/Ice.min.js.gz usr/share/javascript/ice-@mmver@/

usr/lib/Glacier2.min.js usr/share/javascript/ice-@mmver@/
usr/lib/Glacier2.min.js.gz usr/share/javascript/ice-@mmver@/

usr/lib/IceStorm.min.js usr/share/javascript/ice-@mmver@/
usr/lib/IceStorm.min.js.gz usr/share/javascript/ice-@mmver@/

usr/lib/IceGrid.min.js usr/share/javascript/ice-@mmver@/
usr/lib/IceGrid.min.js.gz usr/share/javascript/ice-@mmver@/