usr/share/java/ant-ice-@ver@.jar

usr/bin/slice2java
usr/share/man/man1/slice2java.1

usr/bin/slice2freezej
usr/share/man/man1/slice2freezej.1

usr/share/java/freeze-@ver@.jar
usr/share/java/glacier2-@ver@.jar
usr/share/java/ice-@ver@.jar
usr/share/java/icebox-@ver@.jar
usr/share/java/icediscovery-@ver@.jar
usr/share/java/icegrid-@ver@.jar
usr/share/java/icepatch2-@ver@.jar
usr/share/java/icestorm-@ver@.jar
usr/share/java/ice-gradle-plugin-@ver@.jar

usr/share/maven-repo/com/zeroc/freeze/3.6b/freeze-@ver@.jar
usr/share/maven-repo/com/zeroc/freeze/3.6b/freeze-@ver@.pom

usr/share/maven-repo/com/zeroc/glacier2/3.6b/glacier2-@ver@.jar
usr/share/maven-repo/com/zeroc/glacier2/3.6b/glacier2-@ver@.pom

usr/share/maven-repo/com/zeroc/ice/3.6b/ice-@ver@.jar
usr/share/maven-repo/com/zeroc/ice/3.6b/ice-@ver@.pom

usr/share/maven-repo/com/zeroc/icebox/3.6b/icebox-@ver@.jar
usr/share/maven-repo/com/zeroc/icebox/3.6b/icebox-@ver@.pom

usr/share/maven-repo/com/zeroc/icediscovery/3.6b/icediscovery-@ver@.jar
usr/share/maven-repo/com/zeroc/icediscovery/3.6b/icediscovery-@ver@.pom

usr/share/maven-repo/com/zeroc/icegrid/3.6b/icegrid-@ver@.jar
usr/share/maven-repo/com/zeroc/icegrid/3.6b/icegrid-@ver@.pom

usr/share/maven-repo/com/zeroc/icepatch2/3.6b/icepatch2-@ver@.jar
usr/share/maven-repo/com/zeroc/icepatch2/3.6b/icepatch2-@ver@.pom

usr/share/maven-repo/com/zeroc/icestorm/3.6b/icestorm-@ver@.jar
usr/share/maven-repo/com/zeroc/icestorm/3.6b/icestorm-@ver@.pom
