usr/bin/slice2java
usr/share/man/man1/slice2java.1

usr/bin/slice2freezej
usr/share/man/man1/slice2freezej.1

usr/share/java/ant-ice-3.6.0.jar
usr/share/java/ant-ice-3.6.0-source.jar

usr/share/java/ice-gradle-plugin-3.6.0.jar
usr/share/java/ice-gradle-plugin-3.6.0-source.jar

usr/share/java/freeze-3.6.0.jar
usr/share/java/freeze-3.6.0-source.jar

usr/share/java/glacier2-3.6.0.jar
usr/share/java/glacier2-3.6.0-source.jar

usr/share/java/ice-3.6.0.jar
usr/share/java/ice-3.6.0-source.jar

usr/share/java/icebox-3.6.0.jar
usr/share/java/icebox-3.6.0-source.jar

usr/share/java/icediscovery-3.6.0.jar
usr/share/java/icediscovery-3.6.0-source.jar

usr/share/java/icegrid-3.6.0.jar
usr/share/java/icegrid-3.6.0-source.jar

usr/share/java/icepatch2-3.6.0.jar
usr/share/java/icepatch2-3.6.0-source.jar

usr/share/java/icestorm-3.6.0.jar
usr/share/java/icestorm-3.6.0-source.jar

usr/share/maven-repo/com/zeroc/ant-ice/3.6.0/ant-ice-3.6.0.jar
usr/share/maven-repo/com/zeroc/ant-ice/3.6.0/ant-ice-3.6.0-source.jar
usr/share/maven-repo/com/zeroc/ant-ice/3.6.0/ant-ice-3.6.0.pom

usr/share/maven-repo/com/zeroc/ice-gradle-plugin/3.6.0/ice-gradle-plugin-3.6.0.jar
usr/share/maven-repo/com/zeroc/ice-gradle-plugin/3.6.0/ice-gradle-plugin-3.6.0-source.jar
usr/share/maven-repo/com/zeroc/ice-gradle-plugin/3.6.0/ice-gradle-plugin-3.6.0.pom

usr/share/maven-repo/com/zeroc/freeze/3.6.0/freeze-3.6.0.jar
usr/share/maven-repo/com/zeroc/freeze/3.6.0/freeze-3.6.0-source.jar
usr/share/maven-repo/com/zeroc/freeze/3.6.0/freeze-3.6.0.pom

usr/share/maven-repo/com/zeroc/glacier2/3.6.0/glacier2-3.6.0.jar
usr/share/maven-repo/com/zeroc/glacier2/3.6.0/glacier2-3.6.0-source.jar
usr/share/maven-repo/com/zeroc/glacier2/3.6.0/glacier2-3.6.0.pom

usr/share/maven-repo/com/zeroc/ice/3.6.0/ice-3.6.0.jar
usr/share/maven-repo/com/zeroc/ice/3.6.0/ice-3.6.0-source.jar
usr/share/maven-repo/com/zeroc/ice/3.6.0/ice-3.6.0.pom

usr/share/maven-repo/com/zeroc/icebox/3.6.0/icebox-3.6.0.jar
usr/share/maven-repo/com/zeroc/icebox/3.6.0/icebox-3.6.0-source.jar
usr/share/maven-repo/com/zeroc/icebox/3.6.0/icebox-3.6.0.pom

usr/share/maven-repo/com/zeroc/icediscovery/3.6.0/icediscovery-3.6.0.jar
usr/share/maven-repo/com/zeroc/icediscovery/3.6.0/icediscovery-3.6.0-source.jar
usr/share/maven-repo/com/zeroc/icediscovery/3.6.0/icediscovery-3.6.0.pom

usr/share/maven-repo/com/zeroc/icegrid/3.6.0/icegrid-3.6.0.jar
usr/share/maven-repo/com/zeroc/icegrid/3.6.0/icegrid-3.6.0-source.jar
usr/share/maven-repo/com/zeroc/icegrid/3.6.0/icegrid-3.6.0.pom

usr/share/maven-repo/com/zeroc/icepatch2/3.6.0/icepatch2-3.6.0.jar
usr/share/maven-repo/com/zeroc/icepatch2/3.6.0/icepatch2-3.6.0-source.jar
usr/share/maven-repo/com/zeroc/icepatch2/3.6.0/icepatch2-3.6.0.pom

usr/share/maven-repo/com/zeroc/icestorm/3.6.0/icestorm-3.6.0.jar
usr/share/maven-repo/com/zeroc/icestorm/3.6.0/icestorm-3.6.0-source.jar
usr/share/maven-repo/com/zeroc/icestorm/3.6.0/icestorm-3.6.0.pom
