# Copyright (c) ZeroC, Inc.

from Util import Client, ClientTestCase, MatlabMapping, PhpMapping, TestSuite


class PropertiesTestSuite(TestSuite):
    def setup(self, current):
        if isinstance(self.getMapping(), PhpMapping) or isinstance(self.getMapping(), MatlabMapping):
            return

        name = "\u4e2d\u56fd_client.config"
        current.createFile(
            "./config/" + name,
            [
                "# Automatically generated by Ice test driver.",
                "Ice.Trace.Protocol=1",
                "Ice.Trace.Network=1",
                "Ice.ProgramName=PropertiesClient",
                "Config.Path=./config/" + name,
            ],
            "utf-8",
        )


PropertiesTestSuite(
    __name__,
    [ClientTestCase(client=Client(args=["{testdir}"]))],
    options={
        "ipv6": [False],
        "compress": [False],
        "protocol": ["tcp"],
        "serialize": [False],
        "mx": [False],
    },
)
