# -*- coding: utf-8 -*-
# **********************************************************************
#
# Copyright (c) 2003-present ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************

class PropertiesTestSuite(TestSuite):

    def setup(self, current):
        name = "\xe4\xb8\xad\xe5\x9b\xbd_client.config" if isPython2 else "\u4e2d\u56fd_client.config"
        current.createFile("./config/" + name,
                           ["# Automatically generated by Ice test driver.",
                            "Ice.Trace.Protocol=1",
                            "Ice.Trace.Network=1",
                            "Ice.ProgramName=PropertiesClient",
                            "Config.Path=./config/" + name],
                            "utf-8")

PropertiesTestSuite(__name__, [ ClientTestCase(client=Client(args=["{testdir}"])) ])
