version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      gh-actions:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/js"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7
    groups:
      js-minor-and-patch:
        update-types: ["minor", "patch"]
      js-major:
        update-types: ["major"]

  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7
    groups:
      python-minor-and-patch:
        update-types: ["minor", "patch"]
      python-major:
        update-types: ["major"]

  - package-ecosystem: "pip"
    directory: "/python/docs"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      python-docs:
        patterns: ["*"]

  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7
    groups:
      swift-minor-and-patch:
        update-types: ["minor", "patch"]
      swift-major:
        update-types: ["major"]
