name: Setup Ruby
description: "Setup Ruby environment"

runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
      with:
        ruby-version: "3.4"
