name: Setup Ruby
description: "Setup Ruby environment"

runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
      with:
        ruby-version: "3.4"
