name: Setup .NET Framework
description: "Install .NET Framework Developer/Targeting Packs for building .NET Framework projects"

runs:
  using: "composite"
  steps:
    - name: Install .NET Framework 4.5.1 Developer Pack
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        # Install .NET Framework 4.5.1 Developer Pack using Chocolatey (pre-installed on GitHub runners)
        Write-Host "Installing .NET Framework 4.5.1 Developer Pack via Chocolatey..."
        choco install netfx-4.5.1-devpack -y --no-progress

        # Verify the targeting pack is installed
        $targetingPackPath = "${env:ProgramFiles(x86)}\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1"
        if (Test-Path $targetingPackPath) {
            Write-Host "Targeting pack verified at: $targetingPackPath"
        } else {
            throw "Targeting pack not found at expected location: $targetingPackPath"
        }
