//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// <auto-generated>
//
// Generated from file `EndpointInfo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

import Foundation

/// Provides access to an SSL endpoint information.
public protocol SSLEndpointInfo: EndpointInfo {}
