//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Endpoint.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.zeroc.Ice;

/** Provides access to a WebSocket endpoint information. */
public abstract class WSEndpointInfo extends EndpointInfo {
    public WSEndpointInfo() {
        super();
        this.resource = "";
    }

    public WSEndpointInfo(EndpointInfo underlying, int timeout, boolean compress, String resource) {
        super(underlying, timeout, compress);
        this.resource = resource;
    }

    /** The URI configured with the endpoint. */
    public String resource;

    public WSEndpointInfo clone() {
        return (WSEndpointInfo) super.clone();
    }
}
