#
# Sample configuration file for the IceGrid registry daemon
#

#
# The IceGrid instance name; must be unique, to distinguish several
# IceGrid deployments
#
IceGrid.InstanceName=DemoIceGrid

#
# Client object adapter: listens on the loopback interface
# IANA-registered TCP ports for the IceGrid registry:
# - 4061 (insecure)
# - 4062 (secure, using SSL)
#
# These endpoints must be accessible to Ice clients and servers as
# well as the IceGrid administrative utilities.
#
# To listen on an additional interface add an additional endpoint with
# -h <name | IP address> or remove -h localhost to listen on all
# interfaces.
#
IceGrid.Registry.Client.Endpoints=tcp -p 4061 -h localhost
#IceGrid.Registry.Client.Endpoints=ssl -p 4062 -h localhost
#IceGrid.Registry.Client.Endpoints=tcp -p 4061 -h localhost:ssl -p 4062 -h localhost

#
# Server and Internal object adapters: listens on the loopback
# interface using an OS-assigned port number.
#
# The Server endpoints must be accessible to Ice servers deployed on
# IceGrid nodes or to Ice servers using IceGrid dynamic
# registration. The Internal endpoints must be accessible to IceGrid
# nodes.
#
# To listen on an additional interface add an additional endpoint with
# -h <name | IP address> or remove -h localhost to listen on all
# interfaces. Note that access to these endpoints can pose a security
# risk (remote code execution) and therefore these endpoints should be
# secured. See the Ice manual for more information.
#
IceGrid.Registry.Server.Endpoints=tcp -h localhost
IceGrid.Registry.Internal.Endpoints=tcp -h localhost

#
# The registry DB home; must exist when icegridregistry starts
#
IceGrid.Registry.LMDB.Path=/var/lib/ice/icegrid/registry

#
# Authentication/authorization
# With NullPermissionsVerifier, any password is accepted (not recommended
# for production)
#
IceGrid.Registry.PermissionsVerifier=DemoIceGrid/NullPermissionsVerifier
IceGrid.Registry.AdminPermissionsVerifier=DemoIceGrid/NullPermissionsVerifier

#
# Default templates
#
IceGrid.Registry.DefaultTemplates=/usr/share/ice/templates.xml

#
# Logging to sytemd Journal
#
Ice.UseSystemdJournal=1
Ice.ProgramName=icegridregistry (DemoIceGrid Master)
IceGrid.Registry.Trace.Node=1
IceGrid.Registry.Trace.Replica=1

#
# IceMX configuration
#
IceMX.Metrics.Debug.GroupBy=id
IceMX.Metrics.Debug.Disabled=1
IceMX.Metrics.Debug.Reject.parent=Ice\.Admin
IceMX.Metrics.ByParent.GroupBy=parent
IceMX.Metrics.ByParent.Disabled=1
