.TH icegridgui 1

.SH NAME

icegridgui - The IceGrid graphical administrative utility.

.SH SYNOPSIS

icegridgui [options]

.SH DESCRIPTION

The icegridgui utility is a graphical tool for administering an IceGrid 
domain. Full documentation for icegridgui is available 
online at: 
.br
"https://doc.zeroc.com/display/Ice37/IceGrid+Admin+Graphical+Tool".

.SH SEE ALSO

.BR icegridadmin (1),
.BR icegridnode (1),
.BR icegridregistry (1),
