#
# Sample configuration file for the IceGrid node daemon
#

#
# Proxy to the IceGrid registry
#
Ice.Default.Locator=DemoIceGrid/Locator:tcp -h localhost -p 4061
#Ice.Default.Locator=DemoIceGrid/Locator:ssl -h localhost -p 4062

#
# The name of this node; must be unique within an IceGrid deployment
#
IceGrid.Node.Name=node1

#
# The node object adapter listens on the loopback interface using an
# OS-assigned port
#
# These endpoints must be accessible to IceGrid registries.
#
# To listen on an additional interface add an additional endpoint with
# -h <name | IP address> or remove -h localhost to listen on all
# interfaces. Note that access to these endpoints can pose a security
# risk (remote code execution) and therefore these endpoints should be
# secured. See the Ice manual for more information.
#
IceGrid.Node.Endpoints=tcp -h localhost

#
# The directory where the IceGrid node maintains its data
# (server configuration files etc.)
# This directory must exist when icegridnode starts
#
IceGrid.Node.Data=/var/lib/ice/icegrid/node1

#
# Redirect the servers'stdout and stderr to files in this directory:
#
IceGrid.Node.Output=/var/lib/ice/icegrid/node1
#IceGrid.Node.RedirectErrToOut=1

#
# Logging to syslog
#
Ice.UseSystemdJournal=1
Ice.ProgramName=icegridnode (DemoIceGrid node1)
IceGrid.Node.Trace.Replica=2

#
# IceMX configuration
#
IceMX.Metrics.Debug.GroupBy=id
IceMX.Metrics.Debug.Disabled=1
IceMX.Metrics.Debug.Reject.parent=Ice\.Admin
IceMX.Metrics.ByParent.GroupBy=parent
IceMX.Metrics.ByParent.Disabled=1
