name: "Build DEB Package"
description: "Builds a DEB package using a Docker image"
inputs:
  ice_version:
    description: "The ICE version to build"
    required: true
  deb_build_options:
    description: "DEB_BUILD_OPTIONS for the build"
    required: false
    default: ""
  os:
    description: "The target OS (e.g., ubuntu-24.04, ubuntu-24.04-arm)"
    required: true
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Docker Image
      run: docker build --pull -f ${{ inputs.dockerfile_path }} -t ice-deb-package-builder .
      shell: bash

    - name: Run Package Build with Mounted Source
      run: |
        mkdir -p "$HOME/build"
        docker run --rm \
          -v "$GITHUB_WORKSPACE:/workspace/ice" \
          -v "$HOME/build:/workspace/build" \
          -e ICE_VERSION=${{ inputs.ice_version }} \
          -e DEB_BUILD_OPTIONS="${{ inputs.deb_build_options }}" \
          \ ice-deb-package-builder /workspace/ice/packaging/dpkg/build-package.sh
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deb-packages-${{ inputs.os }}
        path: |
          "$HOME/build/*.deb"
          "$HOME/build/*.ddeb"
          "$HOME/build/*.dsc"
          "$HOME/build/*.tar.xz"
          "$HOME/build/*.tar.gz"
          "$HOME/build/*.changes"
          "$HOME/build/*.buildinfo"
