// **********************************************************************
//
// Copyright (c) 2003-2006 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

#ifndef TAO_PERF_TEST
#define TAO_PERF_TEST

module Test
{
    typedef unsigned long long Timestamp;

    typedef sequence<octet> ByteSeq;

    typedef sequence<string> StringSeq;

    struct StringDouble
    {
	string str;
	double d;
    };
    typedef sequence<StringDouble> StringDoubleSeq;

    //
    // For testing roundtrip RPC performance. Used for both latency and
    // throughput testing.
    //
    interface Roundtrip
    {
	void sendByteSeq(in ByteSeq seq);
	void sendStringSeq(in StringSeq seq);
	void sendStringDoubleSeq(in StringDoubleSeq seq);

	void test_method ();

	oneway void test_oneway();
	oneway void test_oneway_with_data(in ByteSeq seq);

	void shutdown ();
    };
};

#endif /* TAO_PERF_TEST */
