//
// Test.idl,v 1.2 2002/03/09 21:24:29 crodrigu Exp
//

/// A simple module to avoid namespace pollution
module Test
{
  /// Use a timestamp to measure the roundtrip delay
  typedef unsigned long long Timestamp;

  typedef sequence<octet> ByteSeq;

  typedef sequence<string> StringSeq;

  struct StringDouble
  {
     string str;
     double d;
  };
  typedef sequence<StringDouble> StringDoubleSeq;

  /// Measure roundtrip delay
  interface Roundtrip
  {
    void sendByteSeq(in ByteSeq seq);
    void sendStringSeq(in StringSeq seq);
    void sendStringDoubleSeq(in StringDoubleSeq seq);

    /// A simple method to measure roundtrip delays
    /**
     * The operation simply returns its argument, this is used in AMI
     * and deferred synchronous tests to measure the roundtrip delay
     * without the need for a different reply handler for each
     * request.
     */
    void test_method ();

    oneway void test_oneway();

    /// Shutdown the ORB
    void shutdown ();
  };
};
