
TestBase.obj: \
	TestBase.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "TestBase.h" \

CreateTest.obj: \
	CreateTest.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "CreateTest.h" \
    "TestBase.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\Ice\CommunicatorF.h" \
    "$(includedir)\Ice\ProxyF.h" \
    "$(includedir)\Ice\Config.h" \
    "$(includedir)\Ice\ProxyHandle.h" \
    "$(includedir)\Ice\ObjectF.h" \
    "$(includedir)\Ice\Handle.h" \
    "$(includedir)\Ice\ValueF.h" \
    "$(includedir)\Ice\Exception.h" \
    "$(includedir)\Ice\Format.h" \
    "$(includedir)\Ice\StreamF.h" \
    "$(includedir)\Ice\LocalObject.h" \
    "$(includedir)\Ice\LocalObjectF.h" \
    "$(includedir)\Ice\StreamHelpers.h" \
    "$(includedir)\IceUtil\Iterator.h" \
    "$(includedir)\Ice\Traits.h" \
    "$(includedir)\IceUtil\Optional.h" \
    "$(includedir)\IceUtil\UndefSysMacros.h" \

AliveTest.obj: \
	AliveTest.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "AliveTest.h" \
    "TestBase.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\Ice\CommunicatorF.h" \
    "$(includedir)\Ice\ProxyF.h" \
    "$(includedir)\Ice\Config.h" \
    "$(includedir)\Ice\ProxyHandle.h" \
    "$(includedir)\Ice\ObjectF.h" \
    "$(includedir)\Ice\Handle.h" \
    "$(includedir)\Ice\ValueF.h" \
    "$(includedir)\Ice\Exception.h" \
    "$(includedir)\Ice\Format.h" \
    "$(includedir)\Ice\StreamF.h" \
    "$(includedir)\Ice\LocalObject.h" \
    "$(includedir)\Ice\LocalObjectF.h" \
    "$(includedir)\Ice\StreamHelpers.h" \
    "$(includedir)\IceUtil\Iterator.h" \
    "$(includedir)\Ice\Traits.h" \
    "$(includedir)\IceUtil\Optional.h" \
    "$(includedir)\IceUtil\UndefSysMacros.h" \

StartTest.obj: \
	StartTest.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "StartTest.h" \
    "TestBase.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\Ice\CommunicatorF.h" \
    "$(includedir)\Ice\ProxyF.h" \
    "$(includedir)\Ice\Config.h" \
    "$(includedir)\Ice\ProxyHandle.h" \
    "$(includedir)\Ice\ObjectF.h" \
    "$(includedir)\Ice\Handle.h" \
    "$(includedir)\Ice\ValueF.h" \
    "$(includedir)\Ice\Exception.h" \
    "$(includedir)\Ice\Format.h" \
    "$(includedir)\Ice\StreamF.h" \
    "$(includedir)\Ice\LocalObject.h" \
    "$(includedir)\Ice\LocalObjectF.h" \
    "$(includedir)\Ice\StreamHelpers.h" \
    "$(includedir)\IceUtil\Iterator.h" \
    "$(includedir)\Ice\Traits.h" \
    "$(includedir)\IceUtil\Optional.h" \
    "$(includedir)\IceUtil\UndefSysMacros.h" \

SleepTest.obj: \
	SleepTest.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "SleepTest.h" \
    "TestBase.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\Ice\CommunicatorF.h" \
    "$(includedir)\Ice\ProxyF.h" \
    "$(includedir)\Ice\Config.h" \
    "$(includedir)\Ice\ProxyHandle.h" \
    "$(includedir)\Ice\ObjectF.h" \
    "$(includedir)\Ice\Handle.h" \
    "$(includedir)\Ice\ValueF.h" \
    "$(includedir)\Ice\Exception.h" \
    "$(includedir)\Ice\Format.h" \
    "$(includedir)\Ice\StreamF.h" \
    "$(includedir)\Ice\LocalObject.h" \
    "$(includedir)\Ice\LocalObjectF.h" \
    "$(includedir)\Ice\StreamHelpers.h" \
    "$(includedir)\IceUtil\Iterator.h" \
    "$(includedir)\Ice\Traits.h" \
    "$(includedir)\IceUtil\Optional.h" \
    "$(includedir)\IceUtil\UndefSysMacros.h" \

RecMutexTest.obj: \
	RecMutexTest.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "RecMutexTest.h" \
    "TestBase.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\Ice\CommunicatorF.h" \
    "$(includedir)\Ice\ProxyF.h" \
    "$(includedir)\Ice\Config.h" \
    "$(includedir)\Ice\ProxyHandle.h" \
    "$(includedir)\Ice\ObjectF.h" \
    "$(includedir)\Ice\Handle.h" \
    "$(includedir)\Ice\ValueF.h" \
    "$(includedir)\Ice\Exception.h" \
    "$(includedir)\Ice\Format.h" \
    "$(includedir)\Ice\StreamF.h" \
    "$(includedir)\Ice\LocalObject.h" \
    "$(includedir)\Ice\LocalObjectF.h" \
    "$(includedir)\Ice\StreamHelpers.h" \
    "$(includedir)\IceUtil\Iterator.h" \
    "$(includedir)\Ice\Traits.h" \
    "$(includedir)\IceUtil\Optional.h" \
    "$(includedir)\IceUtil\UndefSysMacros.h" \

MutexTest.obj: \
	MutexTest.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "MutexTest.h" \
    "TestBase.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\Ice\CommunicatorF.h" \
    "$(includedir)\Ice\ProxyF.h" \
    "$(includedir)\Ice\Config.h" \
    "$(includedir)\Ice\ProxyHandle.h" \
    "$(includedir)\Ice\ObjectF.h" \
    "$(includedir)\Ice\Handle.h" \
    "$(includedir)\Ice\ValueF.h" \
    "$(includedir)\Ice\Exception.h" \
    "$(includedir)\Ice\Format.h" \
    "$(includedir)\Ice\StreamF.h" \
    "$(includedir)\Ice\LocalObject.h" \
    "$(includedir)\Ice\LocalObjectF.h" \
    "$(includedir)\Ice\StreamHelpers.h" \
    "$(includedir)\IceUtil\Iterator.h" \
    "$(includedir)\Ice\Traits.h" \
    "$(includedir)\IceUtil\Optional.h" \
    "$(includedir)\IceUtil\UndefSysMacros.h" \

MonitorMutexTest.obj: \
	MonitorMutexTest.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "MonitorMutexTest.h" \
    "TestBase.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\Ice\CommunicatorF.h" \
    "$(includedir)\Ice\ProxyF.h" \
    "$(includedir)\Ice\Config.h" \
    "$(includedir)\Ice\ProxyHandle.h" \
    "$(includedir)\Ice\ObjectF.h" \
    "$(includedir)\Ice\Handle.h" \
    "$(includedir)\Ice\ValueF.h" \
    "$(includedir)\Ice\Exception.h" \
    "$(includedir)\Ice\Format.h" \
    "$(includedir)\Ice\StreamF.h" \
    "$(includedir)\Ice\LocalObject.h" \
    "$(includedir)\Ice\LocalObjectF.h" \
    "$(includedir)\Ice\StreamHelpers.h" \
    "$(includedir)\IceUtil\Iterator.h" \
    "$(includedir)\Ice\Traits.h" \
    "$(includedir)\IceUtil\Optional.h" \
    "$(includedir)\IceUtil\UndefSysMacros.h" \

MonitorRecMutexTest.obj: \
	MonitorRecMutexTest.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "MonitorRecMutexTest.h" \
    "TestBase.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\Ice\CommunicatorF.h" \
    "$(includedir)\Ice\ProxyF.h" \
    "$(includedir)\Ice\Config.h" \
    "$(includedir)\Ice\ProxyHandle.h" \
    "$(includedir)\Ice\ObjectF.h" \
    "$(includedir)\Ice\Handle.h" \
    "$(includedir)\Ice\ValueF.h" \
    "$(includedir)\Ice\Exception.h" \
    "$(includedir)\Ice\Format.h" \
    "$(includedir)\Ice\StreamF.h" \
    "$(includedir)\Ice\LocalObject.h" \
    "$(includedir)\Ice\LocalObjectF.h" \
    "$(includedir)\Ice\StreamHelpers.h" \
    "$(includedir)\IceUtil\Iterator.h" \
    "$(includedir)\Ice\Traits.h" \
    "$(includedir)\IceUtil\Optional.h" \
    "$(includedir)\IceUtil\UndefSysMacros.h" \

CountDownLatchTest.obj: \
	CountDownLatchTest.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "$(includedir)\IceUtil\CountDownLatch.h" \
    "CountDownLatchTest.h" \
    "TestBase.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\Ice\CommunicatorF.h" \
    "$(includedir)\Ice\ProxyF.h" \
    "$(includedir)\Ice\Config.h" \
    "$(includedir)\Ice\ProxyHandle.h" \
    "$(includedir)\Ice\ObjectF.h" \
    "$(includedir)\Ice\Handle.h" \
    "$(includedir)\Ice\ValueF.h" \
    "$(includedir)\Ice\Exception.h" \
    "$(includedir)\Ice\Format.h" \
    "$(includedir)\Ice\StreamF.h" \
    "$(includedir)\Ice\LocalObject.h" \
    "$(includedir)\Ice\LocalObjectF.h" \
    "$(includedir)\Ice\StreamHelpers.h" \
    "$(includedir)\IceUtil\Iterator.h" \
    "$(includedir)\Ice\Traits.h" \
    "$(includedir)\IceUtil\Optional.h" \
    "$(includedir)\IceUtil\UndefSysMacros.h" \

TestSuite.obj: \
	TestSuite.cpp \
    "TestSuite.h" \
    "TestBase.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "CountDownLatchTest.h" \
    "MutexTest.h" \
    "RecMutexTest.h" \
    "CreateTest.h" \
    "AliveTest.h" \
    "StartTest.h" \
    "SleepTest.h" \
    "MonitorMutexTest.h" \
    "MonitorRecMutexTest.h" \

Client.obj: \
	Client.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\Ice\CommunicatorF.h" \
    "$(includedir)\Ice\ProxyF.h" \
    "$(includedir)\Ice\Config.h" \
    "$(includedir)\Ice\ProxyHandle.h" \
    "$(includedir)\Ice\ObjectF.h" \
    "$(includedir)\Ice\Handle.h" \
    "$(includedir)\Ice\ValueF.h" \
    "$(includedir)\Ice\Exception.h" \
    "$(includedir)\Ice\Format.h" \
    "$(includedir)\Ice\StreamF.h" \
    "$(includedir)\Ice\LocalObject.h" \
    "$(includedir)\Ice\LocalObjectF.h" \
    "$(includedir)\Ice\StreamHelpers.h" \
    "$(includedir)\IceUtil\Iterator.h" \
    "$(includedir)\Ice\Traits.h" \
    "$(includedir)\IceUtil\Optional.h" \
    "$(includedir)\IceUtil\UndefSysMacros.h" \
    "TestSuite.h" \
    "TestBase.h" \
