
TestBase.obj: \
	TestBase.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\AbstractMutex.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\Cache.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\CountDownLatch.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "TestBase.h" \

ThreadPriority.obj: \
	ThreadPriority.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\AbstractMutex.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\Cache.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\CountDownLatch.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "ThreadPriority.h" \
    "TestBase.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \

TimerPriority.obj: \
	TimerPriority.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\AbstractMutex.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\Cache.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\CountDownLatch.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "TimerPriority.h" \
    "TestBase.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \

PriorityInversion.obj: \
	PriorityInversion.cpp \
    "PriorityInversion.h" \
    "TestBase.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\AbstractMutex.h" \
    "$(includedir)\IceUtil\Cache.h" \
    "$(includedir)\IceUtil\CountDownLatch.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \

TestSuite.obj: \
	TestSuite.cpp \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Config.h" \
    "TestSuite.h" \
    "TestBase.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "ThreadPriority.h" \
    "TimerPriority.h" \
    "PriorityInversion.h" \

Client.obj: \
	Client.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\AbstractMutex.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\Cache.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\CountDownLatch.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "TestSuite.h" \
    "TestBase.h" \
