
TestBase.obj: \
	TestBase.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "TestBase.h" \

ThreadPriority.obj: \
	ThreadPriority.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "ThreadPriority.h" \
    "TestBase.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\Ice\CommunicatorF.h" \
    "$(includedir)\Ice\ProxyF.h" \
    "$(includedir)\Ice\Config.h" \
    "$(includedir)\Ice\ProxyHandle.h" \
    "$(includedir)\Ice\ObjectF.h" \
    "$(includedir)\Ice\Handle.h" \
    "$(includedir)\Ice\ValueF.h" \
    "$(includedir)\Ice\Exception.h" \
    "$(includedir)\Ice\Format.h" \
    "$(includedir)\Ice\StreamF.h" \
    "$(includedir)\Ice\LocalObject.h" \
    "$(includedir)\Ice\LocalObjectF.h" \
    "$(includedir)\Ice\StreamHelpers.h" \
    "$(includedir)\IceUtil\Iterator.h" \
    "$(includedir)\Ice\Traits.h" \
    "$(includedir)\IceUtil\Optional.h" \
    "$(includedir)\IceUtil\UndefSysMacros.h" \

TimerPriority.obj: \
	TimerPriority.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "TimerPriority.h" \
    "TestBase.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\Ice\CommunicatorF.h" \
    "$(includedir)\Ice\ProxyF.h" \
    "$(includedir)\Ice\Config.h" \
    "$(includedir)\Ice\ProxyHandle.h" \
    "$(includedir)\Ice\ObjectF.h" \
    "$(includedir)\Ice\Handle.h" \
    "$(includedir)\Ice\ValueF.h" \
    "$(includedir)\Ice\Exception.h" \
    "$(includedir)\Ice\Format.h" \
    "$(includedir)\Ice\StreamF.h" \
    "$(includedir)\Ice\LocalObject.h" \
    "$(includedir)\Ice\LocalObjectF.h" \
    "$(includedir)\Ice\StreamHelpers.h" \
    "$(includedir)\IceUtil\Iterator.h" \
    "$(includedir)\Ice\Traits.h" \
    "$(includedir)\IceUtil\Optional.h" \
    "$(includedir)\IceUtil\UndefSysMacros.h" \

PriorityInversion.obj: \
	PriorityInversion.cpp \
    "PriorityInversion.h" \
    "TestBase.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\Ice\CommunicatorF.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\Ice\ProxyF.h" \
    "$(includedir)\Ice\Config.h" \
    "$(includedir)\Ice\ProxyHandle.h" \
    "$(includedir)\Ice\ObjectF.h" \
    "$(includedir)\Ice\Handle.h" \
    "$(includedir)\Ice\ValueF.h" \
    "$(includedir)\Ice\Exception.h" \
    "$(includedir)\Ice\Format.h" \
    "$(includedir)\Ice\StreamF.h" \
    "$(includedir)\Ice\LocalObject.h" \
    "$(includedir)\Ice\LocalObjectF.h" \
    "$(includedir)\Ice\StreamHelpers.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Iterator.h" \
    "$(includedir)\Ice\Traits.h" \
    "$(includedir)\IceUtil\Optional.h" \
    "$(includedir)\IceUtil\UndefSysMacros.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \

TestSuite.obj: \
	TestSuite.cpp \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Config.h" \
    "TestSuite.h" \
    "TestBase.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "ThreadPriority.h" \
    "TimerPriority.h" \
    "PriorityInversion.h" \

Client.obj: \
	Client.cpp \
    "$(includedir)\IceUtil\IceUtil.h" \
    "$(includedir)\IceUtil\PushDisableWarnings.h" \
    "$(includedir)\IceUtil\Config.h" \
    "$(includedir)\IceUtil\Cond.h" \
    "$(includedir)\IceUtil\Time.h" \
    "$(includedir)\IceUtil\ThreadException.h" \
    "$(includedir)\IceUtil\Exception.h" \
    "$(includedir)\IceUtil\CtrlCHandler.h" \
    "$(includedir)\IceUtil\Functional.h" \
    "$(includedir)\IceUtil\Handle.h" \
    "$(includedir)\IceUtil\Lock.h" \
    "$(includedir)\IceUtil\Monitor.h" \
    "$(includedir)\IceUtil\MutexProtocol.h" \
    "$(includedir)\IceUtil\Mutex.h" \
    "$(includedir)\IceUtil\MutexPtrLock.h" \
    "$(includedir)\IceUtil\RecMutex.h" \
    "$(includedir)\IceUtil\ScopedArray.h" \
    "$(includedir)\IceUtil\Shared.h" \
    "$(includedir)\IceUtil\Atomic.h" \
    "$(includedir)\IceUtil\StringConverter.h" \
    "$(includedir)\IceUtil\Thread.h" \
    "$(includedir)\IceUtil\Timer.h" \
    "$(includedir)\IceUtil\UUID.h" \
    "$(includedir)\IceUtil\UniquePtr.h" \
    "$(includedir)\IceUtil\PopDisableWarnings.h" \
    "$(top_srcdir)\test\include\TestCommon.h" \
    "$(includedir)\Ice\CommunicatorF.h" \
    "$(includedir)\Ice\ProxyF.h" \
    "$(includedir)\Ice\Config.h" \
    "$(includedir)\Ice\ProxyHandle.h" \
    "$(includedir)\Ice\ObjectF.h" \
    "$(includedir)\Ice\Handle.h" \
    "$(includedir)\Ice\ValueF.h" \
    "$(includedir)\Ice\Exception.h" \
    "$(includedir)\Ice\Format.h" \
    "$(includedir)\Ice\StreamF.h" \
    "$(includedir)\Ice\LocalObject.h" \
    "$(includedir)\Ice\LocalObjectF.h" \
    "$(includedir)\Ice\StreamHelpers.h" \
    "$(includedir)\IceUtil\Iterator.h" \
    "$(includedir)\Ice\Traits.h" \
    "$(includedir)\IceUtil\Optional.h" \
    "$(includedir)\IceUtil\UndefSysMacros.h" \
    "TestSuite.h" \
    "TestBase.h" \
