etc/init.d/icegridnode
etc/init.d/icegridregistry

etc/icegridnode.conf
etc/icegridregistry.conf

usr/bin/icegridnode
usr/share/man/man1/icegridnode.1
usr/bin/icegridregistry
usr/share/man/man1/icegridregistry.1

usr/share/Ice-3.6.0/icegrid-slice.3.5.ice.gz
usr/share/Ice-3.6.0/icegrid-slice.3.6.ice.gz

usr/share/Ice-3.6.0/templates.xml
usr/share/Ice-3.6.0/upgradeicegrid36.py

var/lib/ice/icegrid/registry/
var/lib/ice/icegrid/node1/
