//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.8.50
//
// <auto-generated>
//
// Generated from file `EndpointF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

export namespace Ice
{
    /**
     * A sequence of endpoints.
     */
    type EndpointSeq = Ice.Endpoint[];

    class EndpointSeqHelper
    {
        static write(outs:OutputStream, value:EndpointSeq):void;
        static read(ins:InputStream):EndpointSeq;
    }
}
