name: Setup Java
description: Installs Oracle Java 17 using the actions/setup-java action.
runs:
  using: "composite"
  steps:
    - name: Setup Oracle Java 17
      uses: actions/setup-java@v4
      with:
        distribution: "oracle"
        java-version: "17"
