<?php
// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `Test.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


if(!class_exists('Test_Default'))
{
    class Test_Default extends Ice_ObjectImpl
    {
        public function __construct($x=10, $y=10)
        {
            $this->x = $x;
            $this->y = $y;
        }

        public static function ice_staticId()
        {
            return '::Test::Default';
        }

        public function __toString()
        {
            global $Test__t_Default;
            return IcePHP_stringify($this, $Test__t_Default);
        }

        public $x;
        public $y;
    }

    class Test_DefaultPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::Test::Default', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Test::Default', $facet);
        }
    }

    $Test__t_Default = IcePHP_defineClass('::Test::Default', 'Test_Default', -1, false, false, $Ice__t_Object, null, array(
        array('x', $IcePHP__t_int, false, 0),
        array('y', $IcePHP__t_int, false, 0)));

    $Test__t_DefaultPrx = IcePHP_defineProxy($Test__t_Default);
}

if(!class_exists('Test_NoDefault'))
{
    class Test_NoDefault extends Ice_ObjectImpl
    {
        public function __construct($x=0, $y=0)
        {
            $this->x = $x;
            $this->y = $y;
        }

        public static function ice_staticId()
        {
            return '::Test::NoDefault';
        }

        public function __toString()
        {
            global $Test__t_NoDefault;
            return IcePHP_stringify($this, $Test__t_NoDefault);
        }

        public $x;
        public $y;
    }

    class Test_NoDefaultPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::Test::NoDefault', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Test::NoDefault', $facet);
        }
    }

    $Test__t_NoDefault = IcePHP_defineClass('::Test::NoDefault', 'Test_NoDefault', -1, false, false, $Ice__t_Object, null, array(
        array('x', $IcePHP__t_int, false, 0),
        array('y', $IcePHP__t_int, false, 0)));

    $Test__t_NoDefaultPrx = IcePHP_defineProxy($Test__t_NoDefault);
}

if(!class_exists('Test_PhpOnly'))
{
    class Test_PhpOnly extends Ice_ObjectImpl
    {
        public function __construct($lang="php", $version=30500)
        {
            $this->lang = $lang;
            $this->version = $version;
        }

        public static function ice_staticId()
        {
            return '::Test::PhpOnly';
        }

        public function __toString()
        {
            global $Test__t_PhpOnly;
            return IcePHP_stringify($this, $Test__t_PhpOnly);
        }

        public $lang;
        public $version;
    }

    class Test_PhpOnlyPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::Test::PhpOnly', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::Test::PhpOnly', $facet);
        }
    }

    $Test__t_PhpOnly = IcePHP_defineClass('::Test::PhpOnly', 'Test_PhpOnly', -1, false, false, $Ice__t_Object, null, array(
        array('lang', $IcePHP__t_string, false, 0),
        array('version', $IcePHP__t_int, false, 0)));

    $Test__t_PhpOnlyPrx = IcePHP_defineProxy($Test__t_PhpOnly);
}
?>
