name: Setup C++
description: Installs C++ build dependencies and configures the build environment for the current platform.

inputs:
  profile:
    description: >
      The dependency profile to install.
      'full' installs all C++ dependencies (default).
      'pip-bdist' installs only the minimal dependencies needed to build a pip wheel from sdist.
    default: "full"

runs:
  using: "composite"
  steps:
    - name: Install dependencies on macOS
      if: runner.os == 'macOS' && inputs.profile == 'full'
      shell: bash
      run: brew install mcpp lmdb

    - name: Install dependencies on Linux
      if: runner.os == 'Linux' && inputs.profile == 'full'
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y \
            libbz2-dev libssl-dev libffi-dev \
            libmcpp-dev libedit-dev liblmdb-dev libexpat1-dev libsystemd-dev \
            libbluetooth-dev libdbus-1-dev \
            gdb

    - name: Install pip bdist dependencies on Linux
      if: runner.os == 'Linux' && inputs.profile == 'pip-bdist'
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y \
            libbz2-dev libssl-dev

    # This is needed for GDB to work on Linux runners
    - name: Disable ptrace protection on Linux
      if: runner.os == 'Linux' && inputs.profile == 'full'
      shell: bash
      run: echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope

    - name: Set macOS MAKEFLAGS
      run: echo "MAKEFLAGS=-j$(sysctl -n hw.ncpu) V=1" >> $GITHUB_ENV
      shell: bash
      if: runner.os == 'macOS'

    - name: Set Linux MAKEFLAGS
      run: echo "MAKEFLAGS=-j$(nproc) V=1" >> $GITHUB_ENV
      shell: bash
      if: runner.os == 'Linux'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
      if: runner.os == 'Windows'
