//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `EndpointSelectionType.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


using _System = global::System;

#pragma warning disable 1591

namespace Ice
{
    /// <summary>
    /// Determines the order in which the Ice run time uses the endpoints in a proxy when establishing a connection.
    /// </summary>

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.10")]
    public enum EndpointSelectionType
    {
        /// <summary>
        /// Random causes the endpoints to be arranged in a random order.
        /// </summary>

        Random,
        /// <summary>
        /// Ordered forces the Ice run time to use the endpoints in the order they appeared in the proxy.
        /// </summary>

        Ordered
    }
}
