// **********************************************************************
//
// Copyright (c) 2003-2014 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

#ifndef PERF_IDL
#define PERF_IDL

module Perf
{

enum AEnum
{
    A, 
    B,
    C
};

struct AStruct
{
    AEnum e;
    string s;
    double d;
};

typedef sequence<AStruct> AStructSeq;

struct Event
{
    long long time;
    AEnum e;
    long i;
    AStruct s;
};

interface Ping
{
    void tickVoid(in long long time);

    void tick(in long long time, in AEnum e, in long i, in AStruct s);
};

};

#endif
