// Copyright (c) ZeroC, Inc.

// Generated by scripts/generateIcePyDocs.py from python/python/IcePy-stubs/__init__.pyi. Do not edit.

#ifndef ICEPY_DOC_STRINGS_H
#define ICEPY_DOC_STRINGS_H

// clang-format off

inline constexpr const char* IcePy_DOC_module = "The Internet Communications Engine.";

inline constexpr const char* IcePy_DOC_AsyncInvocationContext = "IcePy.AsyncInvocationContext";

inline constexpr const char* IcePy_DOC_AsyncInvocationContext_cancel = "cancel() -> None";

inline constexpr const char* IcePy_DOC_BatchRequest = R"doc(Represents a batch request.
A batch request is created by invoking an operation on a batch-oneway or batch-datagram proxy.)doc";

inline constexpr const char* IcePy_DOC_BatchRequest_enqueue = R"doc(enqueue() -> None

Queues this request.)doc";

inline constexpr const char* IcePy_DOC_BatchRequest_getOperation = R"doc(getOperation() -> str

Gets the name of the operation.

Returns
-------
str
    The operation name.)doc";

inline constexpr const char* IcePy_DOC_BatchRequest_getProxy = R"doc(getProxy() -> Ice.ObjectPrx

Gets the proxy used to create this batch request.

Returns
-------
Ice.ObjectPrx
    The proxy.)doc";

inline constexpr const char* IcePy_DOC_BatchRequest_getSize = R"doc(getSize() -> int

Gets the size of the request.

Returns
-------
int
    The number of bytes consumed by the request.)doc";

inline constexpr const char* IcePy_DOC_Communicator = "Communicator(initData: Ice.InitializationData | None, /) -> None";

inline constexpr const char* IcePy_DOC_Communicator__getWrapper = "_getWrapper() -> Ice.Communicator";

inline constexpr const char* IcePy_DOC_Communicator__setWrapper = "_setWrapper(wrapper: Ice.Communicator, /) -> None";

inline constexpr const char* IcePy_DOC_Communicator_addAdminFacet = "addAdminFacet(servant: Ice.Object, facet: str, /) -> None";

inline constexpr const char* IcePy_DOC_Communicator_createAdmin = "createAdmin(adminAdapter: Ice.ObjectAdapter | None, adminIdentity: Ice.Identity, /) -> Ice.ObjectPrx";

inline constexpr const char* IcePy_DOC_Communicator_createObjectAdapter = "createObjectAdapter(name: str, /) -> ObjectAdapter";

inline constexpr const char* IcePy_DOC_Communicator_createObjectAdapterWithEndpoints = "createObjectAdapterWithEndpoints(name: str, endpoints: str, /) -> ObjectAdapter";

inline constexpr const char* IcePy_DOC_Communicator_createObjectAdapterWithRouter = "createObjectAdapterWithRouter(name: str, router: Ice.RouterPrx, /) -> ObjectAdapter";

inline constexpr const char* IcePy_DOC_Communicator_destroy = "destroy() -> None";

inline constexpr const char* IcePy_DOC_Communicator_destroyAsync = "destroyAsync(callable: Callable, /) -> None";

inline constexpr const char* IcePy_DOC_Communicator_findAdminFacet = "findAdminFacet(facet: str, /) -> Ice.Object | NativePropertiesAdmin | None";

inline constexpr const char* IcePy_DOC_Communicator_findAllAdminFacets = "findAllAdminFacets() -> dict[str, Ice.Object | NativePropertiesAdmin]";

inline constexpr const char* IcePy_DOC_Communicator_flushBatchRequests = "flushBatchRequests(compress: Ice.CompressBatch, /) -> None";

inline constexpr const char* IcePy_DOC_Communicator_flushBatchRequestsAsync = "flushBatchRequestsAsync(compress: Ice.CompressBatch, /) -> Awaitable[None]";

inline constexpr const char* IcePy_DOC_Communicator_getAdmin = "getAdmin() -> Ice.ObjectPrx | None";

inline constexpr const char* IcePy_DOC_Communicator_getDefaultLocator = "getDefaultLocator() -> Ice.LocatorPrx | None";

inline constexpr const char* IcePy_DOC_Communicator_getDefaultObjectAdapter = "getDefaultObjectAdapter() -> Ice.ObjectAdapter | None";

inline constexpr const char* IcePy_DOC_Communicator_getDefaultRouter = "getDefaultRouter() -> Ice.RouterPrx | None";

inline constexpr const char* IcePy_DOC_Communicator_getImplicitContext = "getImplicitContext() -> ImplicitContext | None";

inline constexpr const char* IcePy_DOC_Communicator_getLogger = "getLogger() -> Ice.Logger | Logger";

inline constexpr const char* IcePy_DOC_Communicator_getProperties = "getProperties() -> Properties";

inline constexpr const char* IcePy_DOC_Communicator_identityToString = "identityToString(identity: Ice.Identity, /) -> str";

inline constexpr const char* IcePy_DOC_Communicator_isShutdown = "isShutdown() -> bool";

inline constexpr const char* IcePy_DOC_Communicator_propertyToProxy = "propertyToProxy(property: str, /) -> Ice.ObjectPrx | None";

inline constexpr const char* IcePy_DOC_Communicator_proxyToProperty = "proxyToProperty(proxy: Ice.ObjectPrx, property: str, /) -> dict[str, str]";

inline constexpr const char* IcePy_DOC_Communicator_proxyToString = "proxyToString(proxy: Ice.ObjectPrx | None, /) -> str";

inline constexpr const char* IcePy_DOC_Communicator_removeAdminFacet = "removeAdminFacet(facet: str, /) -> Ice.Object | None";

inline constexpr const char* IcePy_DOC_Communicator_setDefaultLocator = "setDefaultLocator(locator: Ice.LocatorPrx | None, /) -> None";

inline constexpr const char* IcePy_DOC_Communicator_setDefaultObjectAdapter = "setDefaultObjectAdapter(adapter: Ice.ObjectAdapter | None, /) -> None";

inline constexpr const char* IcePy_DOC_Communicator_setDefaultRouter = "setDefaultRouter(router: Ice.RouterPrx | None, /) -> None";

inline constexpr const char* IcePy_DOC_Communicator_shutdown = "shutdown() -> None";

inline constexpr const char* IcePy_DOC_Communicator_shutdownCompleted = "shutdownCompleted() -> Awaitable[None]";

inline constexpr const char* IcePy_DOC_Communicator_stringToProxy = "stringToProxy(str: str, /) -> Ice.ObjectPrx | None";

inline constexpr const char* IcePy_DOC_Communicator_waitForShutdown = "waitForShutdown(timeout: int, /) -> bool";

inline constexpr const char* IcePy_DOC_Connection = "Represents a connection that uses the Ice protocol.";

inline constexpr const char* IcePy_DOC_Connection_abort = R"doc(abort() -> None

Aborts this connection.)doc";

inline constexpr const char* IcePy_DOC_Connection_close = R"doc(close() -> Awaitable[None]

Starts a graceful closure of this connection once all outstanding invocations have completed.

Returns
-------
Awaitable[None]
    A future that becomes available when the connection is closed. If the connection was lost or
    aborted, awaiting this future raises the exception that caused the connection's closure.)doc";

inline constexpr const char* IcePy_DOC_Connection_createProxy = R"doc(createProxy(identity: Ice.Identity, /) -> Ice.ObjectPrx

Creates a special proxy (a 'fixed proxy') that always uses this connection.

Parameters
----------
identity : Ice.Identity
    The identity of the target object.

Returns
-------
Ice.ObjectPrx
    A fixed proxy with the provided identity.

Raises
------
CommunicatorDestroyedException
    If the communicator has been destroyed.)doc";

inline constexpr const char* IcePy_DOC_Connection_disableInactivityCheck = R"doc(disableInactivityCheck() -> None

Disables the inactivity check on this connection.

By default, Ice will close connections that remain inactive for a certain period.
This method disables that behavior for this connection.)doc";

inline constexpr const char* IcePy_DOC_Connection_setAdapter = R"doc(setAdapter(adapter: Ice.ObjectAdapter | None, /) -> None

Associates an object adapter with this connection.

When a connection receives a request, it dispatches this request using its associated object adapter.
If the associated object adapter is ``None``, the connection rejects any incoming request with an
:class:`Ice.ObjectNotExistException`.

The default object adapter of an incoming connection is the object adapter that created this connection;
the default object adapter of an outgoing connection is the communicator's default object adapter.

Parameters
----------
adapter : Ice.ObjectAdapter | None
    The object adapter to associate with this connection.

Raises
------
LocalException
    If this connection is an incoming (server) connection: only outgoing (client) connections
    support setting the object adapter.)doc";

inline constexpr const char* IcePy_DOC_Connection_getAdapter = R"doc(getAdapter() -> Ice.ObjectAdapter | None

Gets the object adapter associated with this connection.

Returns
-------
Ice.ObjectAdapter | None
    The object adapter associated with this connection.)doc";

inline constexpr const char* IcePy_DOC_Connection_flushBatchRequests = R"doc(flushBatchRequests(compress: Ice.CompressBatch, /) -> None

Flushes any pending batch requests for this connection.

This corresponds to all batch requests invoked on fixed proxies associated with the connection.

Parameters
----------
compress : Ice.CompressBatch
    Specifies whether or not the queued batch requests should be compressed before being sent over the wire.

Raises
------
LocalException
    If the flush fails. For example, this method raises CommunicatorDestroyedException if the communicator
    has been destroyed.)doc";

inline constexpr const char* IcePy_DOC_Connection_flushBatchRequestsAsync = R"doc(flushBatchRequestsAsync(compress: Ice.CompressBatch, /) -> Awaitable[None]

Flushes any pending batch requests for this connection asynchronously.

This corresponds to all batch requests invoked on fixed proxies associated with the connection.

Parameters
----------
compress : Ice.CompressBatch
    Specifies whether or not the queued batch requests should be compressed before being sent over the wire.

Returns
-------
Awaitable[None]
    A future that becomes available when the flush completes.

Raises
------
CommunicatorDestroyedException
    If the communicator has been destroyed. This exception is raised synchronously.)doc";

inline constexpr const char* IcePy_DOC_Connection_setCloseCallback = R"doc(setCloseCallback(callback: Callable[[Connection], None] | None, /) -> None

Sets a close callback on the connection. The callback is called by the connection when it's closed.
The callback is called from the Ice thread pool associated with the connection.

Parameters
----------
callback : Callable[[Connection], None] | None
    The close callback callable, or ``None`` to remove the current callback.)doc";

inline constexpr const char* IcePy_DOC_Connection_type = R"doc(type() -> str

Returns the connection type. This corresponds to the endpoint type, such as 'tcp', 'udp', etc.

Returns
-------
str
    The type of the connection.)doc";

inline constexpr const char* IcePy_DOC_Connection_toString = R"doc(toString() -> str

Returns a description of the connection as human readable text, suitable for logging or error messages.

Notes
-----
This method remains usable after the connection is closed or aborted.

Returns
-------
str
    The description of the connection as human readable text.)doc";

inline constexpr const char* IcePy_DOC_Connection_getInfo = R"doc(getInfo() -> Ice.ConnectionInfo

Returns the connection information.

Returns
-------
Ice.ConnectionInfo
    The connection information.)doc";

inline constexpr const char* IcePy_DOC_Connection_getEndpoint = R"doc(getEndpoint() -> Ice.Endpoint

Gets the endpoint from which the connection was created.

Returns
-------
Ice.Endpoint
    The endpoint from which the connection was created.)doc";

inline constexpr const char* IcePy_DOC_Connection_setBufferSize = R"doc(setBufferSize(rcvSize: int, sndSize: int, /) -> None

Sets the size of the receive and send buffers.

Parameters
----------
rcvSize : int
    The size of the receive buffer.
sndSize : int
    The size of the send buffer.)doc";

inline constexpr const char* IcePy_DOC_Connection_throwException = R"doc(throwException() -> None

Raises an exception that provides the reason for the closure of this connection. For example, this method
raises :class:`Ice.CloseConnectionException` when the connection was closed gracefully by the peer; it raises
:class:`Ice.ConnectionAbortedException` when the connection is aborted with :meth:`~Ice.Connection.abort`.
This method does nothing if the connection is not yet closing or closed.)doc";

inline constexpr const char* IcePy_DOC_ConnectionInfo = "Base class for all connection info classes.";

inline constexpr const char* IcePy_DOC_ConnectionInfo_underlying = "ConnectionInfo | None: The information of the underlying transport or ``None`` if there's no underlying transport.";

inline constexpr const char* IcePy_DOC_ConnectionInfo_incoming = "bool: ``True`` if this is an incoming connection, ``False`` otherwise.";

inline constexpr const char* IcePy_DOC_ConnectionInfo_adapterName = "str: The name of the adapter associated with the connection.";

inline constexpr const char* IcePy_DOC_ConnectionInfo_connectionId = "str: The connection ID.";

inline constexpr const char* IcePy_DOC_DispatchCallback = "IcePy.DispatchCallback";

inline constexpr const char* IcePy_DOC_DispatchCallback_response = "response(result: Any, /) -> None";

inline constexpr const char* IcePy_DOC_DispatchCallback_exception = "exception(exception: BaseException, /) -> None";

inline constexpr const char* IcePy_DOC_Endpoint = R"doc(An endpoint specifies the address of the server-end of an Ice connection.
An object adapter listens on one or more endpoints and a client establishes a connection to an endpoint.)doc";

inline constexpr const char* IcePy_DOC_Endpoint_toString = R"doc(toString() -> str

Returns a string representation of this endpoint.

Returns
-------
str
    The string representation of this endpoint.)doc";

inline constexpr const char* IcePy_DOC_Endpoint_getInfo = R"doc(getInfo() -> EndpointInfo

Returns this endpoint's information.

Returns
-------
EndpointInfo
    This endpoint's information class.)doc";

inline constexpr const char* IcePy_DOC_EndpointInfo = "Base class for the endpoint info classes.";

inline constexpr const char* IcePy_DOC_EndpointInfo_underlying = "Ice.EndpointInfo | None: The information of the underlying endpoint or ``None`` if there's no underlying endpoint.";

inline constexpr const char* IcePy_DOC_EndpointInfo_compress = "bool: Specifies whether or not compression should be used if available when using this endpoint.";

inline constexpr const char* IcePy_DOC_EndpointInfo_type = R"doc(type() -> int

Returns the type of the endpoint.

Returns
-------
int
    The endpoint type.)doc";

inline constexpr const char* IcePy_DOC_EndpointInfo_datagram = R"doc(datagram() -> bool

Returns whether this endpoint is a datagram endpoint (namely, UDP).

Returns
-------
bool
    ``True`` for a UDP endpoint, ``False`` otherwise.)doc";

inline constexpr const char* IcePy_DOC_EndpointInfo_secure = R"doc(secure() -> bool

Returns whether this endpoint uses SSL.

Returns
-------
bool
    ``True`` for SSL and SSL-based transports, ``False`` otherwise.)doc";

inline constexpr const char* IcePy_DOC_ExceptionInfo = "IcePy.ExceptionInfo";

inline constexpr const char* IcePy_DOC_ExecutorCall = "IcePy.ExecutorCall";

inline constexpr const char* IcePy_DOC_IPConnectionInfo = "Provides access to the connection details of an IP connection.";

inline constexpr const char* IcePy_DOC_IPConnectionInfo_localAddress = "str: The local address.";

inline constexpr const char* IcePy_DOC_IPConnectionInfo_localPort = "int: The local port.";

inline constexpr const char* IcePy_DOC_IPConnectionInfo_remoteAddress = "str: The remote address.";

inline constexpr const char* IcePy_DOC_IPConnectionInfo_remotePort = "int: The remote port.";

inline constexpr const char* IcePy_DOC_IPEndpointInfo = "Provides access to the address details of an IP endpoint.";

inline constexpr const char* IcePy_DOC_IPEndpointInfo_host = "str: The host or address configured with the endpoint.";

inline constexpr const char* IcePy_DOC_IPEndpointInfo_port = "int: The port number.";

inline constexpr const char* IcePy_DOC_IPEndpointInfo_sourceAddress = "str: The source IP address.";

inline constexpr const char* IcePy_DOC_ImplicitContext = "IcePy.ImplicitContext";

inline constexpr const char* IcePy_DOC_ImplicitContext_containsKey = "containsKey(key: str, /) -> bool";

inline constexpr const char* IcePy_DOC_ImplicitContext_get = "get(key: str, /) -> str";

inline constexpr const char* IcePy_DOC_ImplicitContext_getContext = "getContext() -> dict[str, str]";

inline constexpr const char* IcePy_DOC_ImplicitContext_put = "put(key: str, value: str, /) -> str";

inline constexpr const char* IcePy_DOC_ImplicitContext_remove = "remove(key: str, /) -> str";

inline constexpr const char* IcePy_DOC_ImplicitContext_setContext = "setContext(newContext: dict[str, str], /) -> None";

inline constexpr const char* IcePy_DOC_Logger = "IcePy.Logger";

inline constexpr const char* IcePy_DOC_Logger_cloneWithPrefix = "cloneWithPrefix(prefix: str, /) -> Logger";

inline constexpr const char* IcePy_DOC_Logger_error = "error(message: str, /) -> None";

inline constexpr const char* IcePy_DOC_Logger_getPrefix = "getPrefix() -> str";

inline constexpr const char* IcePy_DOC_Logger_print = "print(message: str, /) -> None";

inline constexpr const char* IcePy_DOC_Logger_trace = "trace(category: str, message: str, /) -> None";

inline constexpr const char* IcePy_DOC_Logger_warning = "warning(message: str, /) -> None";

inline constexpr const char* IcePy_DOC_NativePropertiesAdmin = "The default implementation of the 'Properties' admin facet.";

inline constexpr const char* IcePy_DOC_NativePropertiesAdmin_addUpdateCallback = R"doc(addUpdateCallback(callback: Callable[[dict[str, str]], None], /) -> None

Registers an update callback that will be invoked when a property update occurs.

Parameters
----------
callback : Callable[[dict[str, str]], None]
    The callback.)doc";

inline constexpr const char* IcePy_DOC_NativePropertiesAdmin_removeUpdateCallback = R"doc(removeUpdateCallback(callback: Callable[[dict[str, str]], None], /) -> None

Removes a previously registered update callback.

Parameters
----------
callback : Callable[[dict[str, str]], None]
    The callback to remove.)doc";

inline constexpr const char* IcePy_DOC_ObjectAdapter = "IcePy.ObjectAdapter";

inline constexpr const char* IcePy_DOC_ObjectAdapter_activate = "activate() -> None";

inline constexpr const char* IcePy_DOC_ObjectAdapter_add = "add(servant: Ice.Object, id: Ice.Identity, /) -> Ice.ObjectPrx";

inline constexpr const char* IcePy_DOC_ObjectAdapter_addDefaultServant = "addDefaultServant(servant: Ice.Object, category: str, /) -> None";

inline constexpr const char* IcePy_DOC_ObjectAdapter_addFacet = "addFacet(servant: Ice.Object, id: Ice.Identity, facet: str, /) -> Ice.ObjectPrx";

inline constexpr const char* IcePy_DOC_ObjectAdapter_addFacetWithUUID = "addFacetWithUUID(servant: Ice.Object, facet: str, /) -> Ice.ObjectPrx";

inline constexpr const char* IcePy_DOC_ObjectAdapter_addServantLocator = "addServantLocator(locator: Ice.ServantLocator, category: str, /) -> None";

inline constexpr const char* IcePy_DOC_ObjectAdapter_addWithUUID = "addWithUUID(servant: Ice.Object, /) -> Ice.ObjectPrx";

inline constexpr const char* IcePy_DOC_ObjectAdapter_createDirectProxy = "createDirectProxy(identity: Ice.Identity, /) -> Ice.ObjectPrx";

inline constexpr const char* IcePy_DOC_ObjectAdapter_createIndirectProxy = "createIndirectProxy(identity: Ice.Identity, /) -> Ice.ObjectPrx";

inline constexpr const char* IcePy_DOC_ObjectAdapter_createProxy = "createProxy(identity: Ice.Identity, /) -> Ice.ObjectPrx";

inline constexpr const char* IcePy_DOC_ObjectAdapter_deactivate = "deactivate() -> None";

inline constexpr const char* IcePy_DOC_ObjectAdapter_destroy = "destroy() -> None";

inline constexpr const char* IcePy_DOC_ObjectAdapter_find = "find(identity: Ice.Identity, /) -> Ice.Object | None";

inline constexpr const char* IcePy_DOC_ObjectAdapter_findAllFacets = "findAllFacets(id: Ice.Identity, /) -> dict[str, Ice.Object]";

inline constexpr const char* IcePy_DOC_ObjectAdapter_findByProxy = "findByProxy(proxy: Ice.ObjectPrx, /) -> Ice.Object | None";

inline constexpr const char* IcePy_DOC_ObjectAdapter_findDefaultServant = "findDefaultServant(category: str, /) -> Ice.Object | None";

inline constexpr const char* IcePy_DOC_ObjectAdapter_findFacet = "findFacet(id: Ice.Identity, facet: str, /) -> Ice.Object | None";

inline constexpr const char* IcePy_DOC_ObjectAdapter_findServantLocator = "findServantLocator(category: str, /) -> Ice.ServantLocator | None";

inline constexpr const char* IcePy_DOC_ObjectAdapter_getCommunicator = "getCommunicator() -> Communicator";

inline constexpr const char* IcePy_DOC_ObjectAdapter_getEndpoints = "getEndpoints() -> tuple[Endpoint, ...]";

inline constexpr const char* IcePy_DOC_ObjectAdapter_getLocator = "getLocator() -> Ice.LocatorPrx | None";

inline constexpr const char* IcePy_DOC_ObjectAdapter_getName = "getName() -> str";

inline constexpr const char* IcePy_DOC_ObjectAdapter_getPublishedEndpoints = "getPublishedEndpoints() -> tuple[Endpoint, ...]";

inline constexpr const char* IcePy_DOC_ObjectAdapter_hold = "hold() -> None";

inline constexpr const char* IcePy_DOC_ObjectAdapter_isDeactivated = "isDeactivated() -> bool";

inline constexpr const char* IcePy_DOC_ObjectAdapter_remove = "remove(id: Ice.Identity, /) -> Ice.Object";

inline constexpr const char* IcePy_DOC_ObjectAdapter_removeAllFacets = "removeAllFacets(id: Ice.Identity, /) -> dict[str, Ice.Object]";

inline constexpr const char* IcePy_DOC_ObjectAdapter_removeDefaultServant = "removeDefaultServant(category: str, /) -> Ice.Object";

inline constexpr const char* IcePy_DOC_ObjectAdapter_removeFacet = "removeFacet(id: Ice.Identity, facet: str, /) -> Ice.Object";

inline constexpr const char* IcePy_DOC_ObjectAdapter_removeServantLocator = "removeServantLocator(category: str, /) -> Ice.ServantLocator";

inline constexpr const char* IcePy_DOC_ObjectAdapter_setLocator = "setLocator(locator: Ice.LocatorPrx | None, /) -> None";

inline constexpr const char* IcePy_DOC_ObjectAdapter_setPublishedEndpoints = "setPublishedEndpoints(newEndpoints: tuple[Endpoint, ...] | list[Endpoint], /) -> None";

inline constexpr const char* IcePy_DOC_ObjectAdapter_waitForDeactivate = "waitForDeactivate(timeout: int, /) -> bool";

inline constexpr const char* IcePy_DOC_ObjectAdapter_waitForHold = "waitForHold(timeout: int, /) -> bool";

inline constexpr const char* IcePy_DOC_ObjectPrx = "ObjectPrx(communicator: Ice.Communicator, proxyString: str, /) -> None";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_adapterId = "ice_adapterId(newAdapterId: str, /) -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_batchDatagram = "ice_batchDatagram() -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_batchOneway = "ice_batchOneway() -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_collocationOptimized = "ice_collocationOptimized(collocated: bool, /) -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_compress = "ice_compress(compress: bool, /) -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_connectionCached = "ice_connectionCached(newCache: bool, /) -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_connectionId = "ice_connectionId(connectionId: str, /) -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_context = "ice_context(new_context: dict[str, str], /) -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_datagram = "ice_datagram() -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_encodingVersion = "ice_encodingVersion(version: Ice.EncodingVersion, /) -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_endpointSelection = "ice_endpointSelection(newType: Ice.EndpointSelectionType, /) -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_endpoints = "ice_endpoints(newEndpoints: tuple[Endpoint, ...] | list[Endpoint], /) -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_facet = "ice_facet(new_facet: str, /) -> Ice.ObjectPrx";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_fixed = "ice_fixed(connection: Ice.Connection, /) -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_flushBatchRequests = "ice_flushBatchRequests() -> None";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_flushBatchRequestsAsync = "ice_flushBatchRequestsAsync() -> Awaitable[None]";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getAdapterId = "ice_getAdapterId() -> str";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getCachedConnection = "ice_getCachedConnection() -> Ice.Connection | None";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getCommunicator = "ice_getCommunicator() -> Ice.Communicator";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getCompress = "ice_getCompress() -> bool | None";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getConnection = "ice_getConnection() -> Ice.Connection | None";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getConnectionAsync = "ice_getConnectionAsync() -> Awaitable[Ice.Connection | None]";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getConnectionId = "ice_getConnectionId() -> str";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getContext = "ice_getContext() -> dict[str, str]";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getEncodingVersion = "ice_getEncodingVersion() -> Ice.EncodingVersion";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getEndpointSelection = "ice_getEndpointSelection() -> Ice.EndpointSelectionType";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getEndpoints = "ice_getEndpoints() -> tuple[Endpoint, ...]";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getFacet = "ice_getFacet() -> str";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getIdentity = "ice_getIdentity() -> Ice.Identity";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getInvocationTimeout = "ice_getInvocationTimeout() -> int";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getLocator = "ice_getLocator() -> Ice.LocatorPrx | None";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getLocatorCacheTimeout = "ice_getLocatorCacheTimeout() -> int";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_getRouter = "ice_getRouter() -> Ice.RouterPrx | None";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_identity = "ice_identity(newIdentity: Ice.Identity, /) -> Ice.ObjectPrx";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_invocationTimeout = "ice_invocationTimeout(timeout: int, /) -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_invoke = "ice_invoke(operation: str, mode: Ice.OperationMode, inParams: bytes, ctx: dict[str, str] | None = None) -> tuple[bool, bytes]";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_invokeAsync = "ice_invokeAsync(operation: str, mode: Ice.OperationMode, inParams: bytes, ctx: dict[str, str] | None = None) -> Awaitable[tuple[bool, bytes]]";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_isBatchDatagram = "ice_isBatchDatagram() -> bool";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_isBatchOneway = "ice_isBatchOneway() -> bool";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_isCollocationOptimized = "ice_isCollocationOptimized() -> bool";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_isConnectionCached = "ice_isConnectionCached() -> bool";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_isDatagram = "ice_isDatagram() -> bool";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_isFixed = "ice_isFixed() -> bool";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_isOneway = "ice_isOneway() -> bool";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_isTwoway = "ice_isTwoway() -> bool";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_locator = "ice_locator(locator: Ice.LocatorPrx | None, /) -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_locatorCacheTimeout = "ice_locatorCacheTimeout(timeout: int, /) -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_oneway = "ice_oneway() -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_router = "ice_router(router: Ice.RouterPrx | None, /) -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_toString = "ice_toString() -> str";

inline constexpr const char* IcePy_DOC_ObjectPrx_ice_twoway = "ice_twoway() -> Self";

inline constexpr const char* IcePy_DOC_ObjectPrx_newProxy = "newProxy(type: Type[T], proxy: Ice.ObjectPrx, /) -> T";

inline constexpr const char* IcePy_DOC_OpaqueEndpointInfo = "Provides access to the details of an opaque endpoint.";

inline constexpr const char* IcePy_DOC_OpaqueEndpointInfo_rawBytes = "bytes: The raw encoding of the opaque endpoint.";

inline constexpr const char* IcePy_DOC_OpaqueEndpointInfo_rawEncoding = "Ice.EncodingVersion: The encoding version of the opaque endpoint (to decode or encode the ``rawBytes``).";

inline constexpr const char* IcePy_DOC_Operation = "Operation(sliceName: str, mappedName: str, mode: Ice.OperationMode, format: Ice.FormatType | None, metadata: tuple, inParams: tuple, outParams: tuple, returnType: object, exceptions: tuple, onewayOnly: bool, /) -> None";

inline constexpr const char* IcePy_DOC_Operation_invoke = "invoke(proxy: ObjectPrx, args: tuple, /) -> Any";

inline constexpr const char* IcePy_DOC_Operation_invokeAsync = "invokeAsync(proxy: ObjectPrx, args: tuple, /) -> Awaitable[Any]";

inline constexpr const char* IcePy_DOC_Operation_deprecate = "deprecate(reason: str, /)";

inline constexpr const char* IcePy_DOC_Properties = "Properties(args: list[str] | None = None, defaults: Ice.Properties | None = None, /) -> None";

inline constexpr const char* IcePy_DOC_Properties_getProperty = "getProperty(key: str, /) -> str";

inline constexpr const char* IcePy_DOC_Properties_getIceProperty = "getIceProperty(key: str, /) -> str";

inline constexpr const char* IcePy_DOC_Properties_getPropertyWithDefault = "getPropertyWithDefault(key: str, value: str, /) -> str";

inline constexpr const char* IcePy_DOC_Properties_getPropertyAsInt = "getPropertyAsInt(key: str, /) -> int";

inline constexpr const char* IcePy_DOC_Properties_getIcePropertyAsInt = "getIcePropertyAsInt(key: str, /) -> int";

inline constexpr const char* IcePy_DOC_Properties_getPropertyAsIntWithDefault = "getPropertyAsIntWithDefault(key: str, value: int, /) -> int";

inline constexpr const char* IcePy_DOC_Properties_getPropertyAsList = "getPropertyAsList(key: str, /) -> list[str]";

inline constexpr const char* IcePy_DOC_Properties_getIcePropertyAsList = "getIcePropertyAsList(key: str, /) -> list[str]";

inline constexpr const char* IcePy_DOC_Properties_getPropertyAsListWithDefault = "getPropertyAsListWithDefault(key: str, value: list[str], /) -> list[str]";

inline constexpr const char* IcePy_DOC_Properties_getPropertiesForPrefix = "getPropertiesForPrefix(prefix: str, /) -> dict[str, str]";

inline constexpr const char* IcePy_DOC_Properties_setProperty = "setProperty(key: str, value: str, /) -> None";

inline constexpr const char* IcePy_DOC_Properties_getCommandLineOptions = "getCommandLineOptions() -> list[str]";

inline constexpr const char* IcePy_DOC_Properties_parseCommandLineOptions = "parseCommandLineOptions(prefix: str, options: list[str], /) -> list[str]";

inline constexpr const char* IcePy_DOC_Properties_parseIceCommandLineOptions = "parseIceCommandLineOptions(options: list[str], /) -> list[str]";

inline constexpr const char* IcePy_DOC_Properties_load = "load(file: str, /) -> None";

inline constexpr const char* IcePy_DOC_Properties_clone = "clone() -> Properties";

inline constexpr const char* IcePy_DOC_SSLConnectionInfo = "Provides access to the connection details of an SSL connection.";

inline constexpr const char* IcePy_DOC_SSLConnectionInfo_peerCertificate = "str: The peer certificate, PEM-encoded, or an empty string if the peer did not provide one.";

inline constexpr const char* IcePy_DOC_SSLEndpointInfo = "Provides access to an SSL endpoint's information.";

inline constexpr const char* IcePy_DOC_TCPConnectionInfo = "Provides access to the connection details of a TCP connection.";

inline constexpr const char* IcePy_DOC_TCPConnectionInfo_rcvSize = "int: The size of the receive buffer.";

inline constexpr const char* IcePy_DOC_TCPConnectionInfo_sndSize = "int: The size of the send buffer.";

inline constexpr const char* IcePy_DOC_TCPEndpointInfo = "Provides access to a TCP endpoint's information.";

inline constexpr const char* IcePy_DOC_UDPConnectionInfo = "Provides access to the connection details of a UDP connection.";

inline constexpr const char* IcePy_DOC_UDPConnectionInfo_mcastAddress = "str: The multicast address.";

inline constexpr const char* IcePy_DOC_UDPConnectionInfo_mcastPort = "int: The multicast port.";

inline constexpr const char* IcePy_DOC_UDPConnectionInfo_rcvSize = "int: The size of the receive buffer.";

inline constexpr const char* IcePy_DOC_UDPConnectionInfo_sndSize = "int: The size of the send buffer.";

inline constexpr const char* IcePy_DOC_UDPEndpointInfo = "Provides access to a UDP endpoint's information.";

inline constexpr const char* IcePy_DOC_UDPEndpointInfo_mcastInterface = "str: The multicast interface.";

inline constexpr const char* IcePy_DOC_UDPEndpointInfo_mcastTtl = "int: The multicast time-to-live (or hops).";

inline constexpr const char* IcePy_DOC_WSConnectionInfo = "Provides access to the connection details of a WebSocket connection.";

inline constexpr const char* IcePy_DOC_WSConnectionInfo_headers = "dict[str, str]: The HTTP headers from the WebSocket upgrade handshake, with the request headers for an incoming connection and the response headers for an outgoing connection.";

inline constexpr const char* IcePy_DOC_WSEndpointInfo = "Provides access to a WebSocket endpoint's information.";

inline constexpr const char* IcePy_DOC_WSEndpointInfo_resource = "str: The URI configured with the endpoint.";

inline constexpr const char* IcePy_DOC_stringVersion = R"doc(stringVersion() -> str

Returns the Ice version in the form ``A.B.C``, where ``A`` indicates the major version, ``B`` indicates the
minor version, and ``C`` indicates the patch level.
For pre-releases, the version includes a pre-release suffix, for example ``3.9.0-alpha.0``.

Returns
-------
str
    The Ice version.)doc";

inline constexpr const char* IcePy_DOC_intVersion = R"doc(intVersion() -> int

Returns the Ice version as an integer in the form ``AABBCC``, where ``AA`` indicates the major version,
``BB`` indicates the minor version, and ``CC`` indicates the patch level.
For example, for Ice 3.9.1, the returned value is 30901.
For pre-releases, ``CC`` encodes the pre-release; for example, for Ice 3.9.0-alpha.0, the returned value
is 30950.

Returns
-------
int
    The Ice version.)doc";

inline constexpr const char* IcePy_DOC_createProperties = R"doc(createProperties(args: list[str] | None = None, defaults: Ice.Properties | None = None, /) -> Properties

Creates a property set initialized from command-line arguments and a default property set.

Parameters
----------
args : list[str] | None, optional
    The command-line arguments.
defaults : Ice.Properties | None, optional
    Default values for the new property set.

Returns
-------
Properties
    A new property set.)doc";

inline constexpr const char* IcePy_DOC_stringToIdentity = R"doc(stringToIdentity(str: str, /) -> Ice.Identity

Converts a stringified identity into an Identity.

Parameters
----------
str : str
    The stringified identity.

Returns
-------
Ice.Identity
    An Identity created from the provided string.

Raises
------
ParseException
    If the string cannot be converted to an object identity.
LocalException
    If the resulting identity has an empty name.)doc";

inline constexpr const char* IcePy_DOC_identityToString = R"doc(identityToString(identity: Ice.Identity, toStringMode: Ice.ToStringMode | None = None, /) -> str

Converts an Identity into a string using the specified mode.

Parameters
----------
identity : Ice.Identity
    The identity.
toStringMode : Ice.ToStringMode | None, optional
    Specifies how to handle non-ASCII characters and non-printable ASCII characters.
    The default is :const:`Ice.ToStringMode.Unicode`.

Returns
-------
str
    The stringified identity.)doc";

inline constexpr const char* IcePy_DOC_getProcessLogger = R"doc(getProcessLogger() -> Ice.Logger | Logger

Gets the per-process logger.

Returns
-------
Ice.Logger | Logger
    The current per-process logger instance.)doc";

inline constexpr const char* IcePy_DOC_setProcessLogger = R"doc(setProcessLogger(logger: Ice.Logger, /) -> None

Sets the per-process logger. Communicators created after this call use this logger unless a logger is set
in InitializationData or configured through logger properties such as Ice.LogFile.

Parameters
----------
logger : Ice.Logger
    The new per-process logger instance.)doc";

inline constexpr const char* IcePy_DOC_loadSlice = R"doc(loadSlice(args: list[str], /) -> None

Compiles Slice definitions and loads the generated code directly into the current Python environment.

This function does not generate any Python source files. Instead, the generated Python code is loaded
directly into the running interpreter.

This function does not generate any code for Slice files included by the Slice files being loaded. It is
the caller's responsibility to load all necessary Slice definitions. This can be done in a single call to
:func:`Ice.loadSlice` by providing all Slice files (including included files) in the `args` parameter, or
by making multiple calls to :func:`Ice.loadSlice`.

When :func:`Ice.loadSlice` is called multiple times with the same Slice file, the corresponding Python
code is not reloaded.

Parameters
----------
args : list[str]
    The list of command-line arguments for the Slice loader. These arguments may include both compiler options and
    the Slice files to compile.

    Supported compiler options:

        - ``-DNAME``:  Define NAME as 1.
        - ``-DNAME=DEF``:  Define NAME as DEF.
        - ``-UNAME``:  Remove any definition for NAME.
        - ``-IDIR``:  Put DIR in the include file search path.
        - ``-d``, ``--debug``:  Print debug messages.

Raises
------
RuntimeError
    If an error occurs during Slice parsing or compilation.)doc";

inline constexpr const char* IcePy_DOC_compileSlice = R"doc(compileSlice(args: list[str], /) -> int

Compiles Slice definitions. The behavior is identical to that of the `slice2py` compiler.

Any errors or warnings emitted during compilation are printed to 'stderr'.

This is an internal function used in the implementation of the `slice2py` Python script included in the
Ice Python package.

Parameters
----------
args : list[str]
    The list of command-line arguments for Slice compilation, following the same syntax as the `slice2py`
    compiler.

Returns
-------
int
    The exit code: 0 indicates success, and a non-zero value indicates failure.)doc";

inline constexpr const char* IcePy_DOC_declareProxy = "declareProxy(sliceId: str, /)";

inline constexpr const char* IcePy_DOC_defineProxy = "defineProxy(sliceId: str, proxyType: Type[ObjectPrx], /)";

inline constexpr const char* IcePy_DOC_declareValue = "declareValue(sliceId: str, /)";

inline constexpr const char* IcePy_DOC_defineValue = "defineValue(sliceId: str, valueType: Type[Ice.Value], compactId: int, meta: tuple, isInterface: bool, baseType: Type[Ice.Value] | None, members: tuple, /)";

inline constexpr const char* IcePy_DOC_defineDictionary = "defineDictionary(sliceId: str, meta: tuple, keyType: TypeInfo, valueType: TypeInfo, /)";

inline constexpr const char* IcePy_DOC_defineEnum = "defineEnum(sliceId: str, type: Type, meta: tuple, enumerators: dict, /)";

inline constexpr const char* IcePy_DOC_defineException = "defineException(sliceId: str, type: Type[BaseException], meta: tuple, base: Type[BaseException] | None, members: tuple, /)";

inline constexpr const char* IcePy_DOC_defineSequence = "defineSequence(sliceId: str, meta: tuple, elementType: TypeInfo, /)";

inline constexpr const char* IcePy_DOC_defineStruct = "defineStruct(sliceId: str, type: Type, meta: tuple, members: tuple, /)";

inline constexpr const char* IcePy_DOC_TypeInfo = "IcePy.TypeInfo";

// clang-format on

#endif
