#!/usr/bin/env bash
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#

# This is a wrapper around Ice Builder for Xcode which is used by the
# iOS C++ and Objective-C Xcode projects to help find binary and source
# distributions.

if [[ "$ICE_BIN_DIST" =~ ^(all|cpp)$ ]]; then
    if [ -n "$ICE_HOME" ]; then
        FLAGS="--ice-home \"$ICE_HOME\""
    fi
else
    FLAGS="--ice-home ../../../.."
fi

if [ -f "/usr/local/bin/icebuilder" ]; then
   ICEBUILDER="/usr/local/bin/icebuilder"
elif [ -f "/opt/homebrew/bin/icebuilder" ]; then
   ICEBUILDER="/opt/homebrew/bin/icebuilder"
else
    echo "Failed to locate ice-builder-xcode"
    echo "see https://github.com/zeroc-ice/ice-builder-xcode for install instructions"
fi


$ICEBUILDER $FLAGS "$@"
