#!/usr/bin/env bash
# Copyright (c) ZeroC, Inc.

# This is a wrapper around Ice Builder for Xcode which is used by the
# iOS C++ Xcode projects to help find binary and source distributions.

FLAGS="--ice-home ../../../.."

if [ -f "/usr/local/bin/icebuilder" ]; then
   ICEBUILDER="/usr/local/bin/icebuilder"
elif [ -f "/opt/homebrew/bin/icebuilder" ]; then
   ICEBUILDER="/opt/homebrew/bin/icebuilder"
else
    echo "Failed to locate ice-builder-xcode"
    echo "see https://github.com/zeroc-ice/ice-builder-xcode for install instructions"
fi

$ICEBUILDER $FLAGS "$@"
