/*
 * This source file was generated by the Gradle 'init' task
 */
package com.zeroc

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.zeroc.slice-tools-java' plugin.
 */
class SliceToolsJavaPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("java")
        project.plugins.apply("com.zeroc.slice-tools-java")

        // Verify the result
        assertNotNull(project.tasks.findByName("compileSlice"))

    }
}
