#!/usr/bin/env ruby
# **********************************************************************
#
# Copyright (c) 2003-present ZeroC, Inc. All rights reserved.
#
# **********************************************************************

require 'Ice'
sliceDir = Ice.getSliceDir()
if sliceDir != nil
    ARGV << "-I" + sliceDir
end
rc = Ice::compile(ARGV)
exit(rc)
