name: "Build Slice Compiler"
description: "Builds a Slice compiler from C++ source for multiple platforms"

inputs:
  compiler-name:
    description: "Name of the compiler to build"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build on Windows
      if: runner.os == 'Windows'
      run: |
        MSBuild cpp/msbuild/ice.proj /p:Configuration=Release /p:Platform=x64 /t:${{ inputs.compiler-name }}
      shell: cmd

    - name: Build on Linux/macOS
      if: runner.os != 'Windows'
      run: |
        make -C cpp OPTIMIZE=yes V=1 ${{ inputs.compiler-name }}
      shell: bash
