name: Windows Debug Tools Installer
runs:
  using: "composite"
  steps:
    - name: Install Debugging Tools via Visual Studio Installer
      shell: pwsh
      run: |
        $sdkPath = "$env:TEMP\sdksetup.exe"

        Write-Host "Downloading Windows SDK installer..."
        Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2338977" -OutFile $sdkPath

        Write-Host "Running Windows SDK installer (Debugging Tools only)..."
        $args = '/quiet /norestart /features OptionId.WindowsDesktopDebuggers /log "{0}"' -f sdk-install.log
        $p = Start-Process -FilePath $sdkPath -ArgumentList $args -PassThru -Wait

    - name: Upload SDK install log
      if: failed()
      uses: actions/upload-artifact@v4
      with:
        name: sdk-install-log
        path: sdk-install.log
