.TH dsnode 1

.SH NAME
dsnode - The DataStorm Node server.

.SH SYNOPSIS
.B dsnode
.RI [ options ]

.SH DESCRIPTION
The DataStorm node server allows other DataStorm nodes to exchange
topic discovery information without relying on UDP multicast. It
also helps create deployments that span multiple IP networks.

Full documentation for the DataStorm Node server is available online at:
.br
.UR https://doc.zeroc.com/ice/3.7/ice-services/dsnode
.UE

.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Displays the help message.

.TP
.BR \-v ", " \-\-version
Displays the Ice version.
