.TH dsnode 1

.SH NAME

dsnode - The DataStorm Node server.

.SH SYNOPSIS

dsnode [options]

.SH DESCRIPTION

The DataStorm node server allows discovering of registered nodes, and provides bridging of nodes with disabled server
endpoints. Full documentation for DataStorm Node server is available online at:
.br
https://doc.zeroc.com/ice/3.7/ice-services/dsnode

.SH OPTIONS

.TP
.BR \-h ", " \-\-help\fR
.br
Displays help message.

.TP
.BR \-v ", " \-\-version\fR
Displays the Ice version.
