.TH glacier2router 1

.SH NAME

glacier2router - The Glacier2 router daemon.

.SH SYNOPSIS

glacier2router [options]

.SH DESCRIPTION

Glacier2 is a lightweight firewall traversal solution for Ice applications.
Full documentation for Glacier2 is available online at:
.br
https://doc.zeroc.com/ice/3.7/ice-services/glacier2

.SH OPTIONS

.TP
.BR \-h ", " \-\-help\fR
.br
Displays help message.

.TP
.BR \-v ", " \-\-version\fR
Displays the Ice version.

.TP
.BR \-\-nowarn\fR
.br
Suppress warnings.

.TP
.BR \-\-daemon\fR
.br
Run as a daemon.

.TP
.BR \-\-pidfile " " FILE
.br
Write process ID into FILE.

.TP
.BR \-\-noclose\fR
.br
Do not close open file descriptors.

.TP
.BR \-\-nochdir\fR
.br
Do not change the current working directory.
