.mso www.tmac

.TH iceboxadmin 1

.SH NAME

iceboxadmin - The IceBox administrative utility.

.SH SYNOPSIS

iceboxadmin [options] [command...]

.SH DESCRIPTION

The IceBox administrative utility. Full documentation for iceboxadmin is
available online at:
.br
https://doc.zeroc.com/display/Ice37/IceBox+Administration

.SH OPTIONS

.TP
.BR \-h ", " \-\-help\fR
.br
Displays a help message.

.TP
.BR \-v ", " \-\-version\fR
Displays the Ice version.

.SH COMMANDS

.TP
.BR start " " SERVICE\fR
.br
Start a service.

.TP
.BR stop " " SERVICE\fR
.br
Stop a service.

.TP
.BR shutdown\fR
.br
Shutdown the server.

.SH SEE ALSO

.BR icebox (1)
