.TH iceboxnet 1

.SH NAME

iceboxnet - The IceBox .NET/Mono Server.

.SH SYNOPSIS

iceboxnet [options] --Ice.Config=<file>

.SH DESCRIPTION

The IceBox .NET Server. For detailed usage consult:
.br
https://doc.zeroc.com/ice/3.6/icebox/starting-the-icebox-server

.SH SEE ALSO

.BR icebox (1),
.BR iceboxadmin (1)
