.TH icebridge 1

.SH NAME

icebridge - The IceBridge daemon.

.SH SYNOPSIS

icebridge [options]

.SH DESCRIPTION

IceBridge acts as a bridge between one or more clients and a server.
Full documentation for IceBridge is available online at:
.br
https://doc.zeroc.com/ice/3.7/ice-services/icebridge

.SH OPTIONS

.TP
.BR \-h ", " \-\-help\fR
.br
Displays help message.

.TP
.BR \-v ", " \-\-version\fR
Displays the Ice version.

.TP
.BR \-\-daemon\fR
.br
Run as a daemon.

.TP
.BR \-\-pidfile " " FILE
.br
Write process ID into FILE.

.TP
.BR \-\-noclose\fR
.br
Do not close open file descriptors.

.TP
.BR \-\-nochdir\fR
.br
Do not change the current working directory.
