.TH icebox 1

.SH NAME
icebox - The IceBox C++ service daemon.

.SH SYNOPSIS

icebox [options]

.SH DESCRIPTION

IceBox is an easy-to-use framework for Ice application services. Full
documentation for IceBox is available online at:
.br
https://doc.zeroc.com/display/Ice37/IceBox

.SH OPTIONS

.TP
.BR \-h ", " \-\-help\fR
.br
Displays a help message.

.TP
.BR \-v ", " \-\-version\fR
Displays the Ice version.

.TP
.BR \-\-nowarn\fR
.br
Suppress warnings.

.TP
.BR \-\-daemon\fR
.br
Run as a daemon.

.TP
.BR \-\-pidfile " " FILE
.br
Write process ID into FILE.

.TP
.BR \-\-noclose\fR
.br
Do not close open file descriptors.

.TP
.BR \-\-nochdir\fR
.br
Do not change the current working directory.

.SH SEE ALSO

.BR iceboxadmin (1)
