.TH icegriddb 1

.SH NAME

icegriddb - The IceGrid database import/export utility.

.SH SYNOPSIS

icegriddb [options]

.SH DESCRIPTION

The icegriddb utility is a command-line tool for importing and exporting IceGrid
databases. Full documentation for icegriddb is available
online at:
.br
https://doc.zeroc.com/display/Ice37/icegriddb+Command+Line+Tool

.SH OPTIONS

.TP
.BR \-h ", " \-\-help\fR
.br
Show program help.

.TP
.BR \-v ", " \-\-version\fR
.br
Display the Ice version.

.TP
.BR \-d ", " \-\-debug\fR
.br
Print debug messages.

.TP
.BR \-\-import " " FILE\fR
.br
Import database from specifed file.

.TP
.BR \-\-export " " FILE\fR
.br
Export database to specified file.

.TP
.BR \-\-dbhome " " DIR\fR
.br
The database directory.

.TP
.BR \-\-server\-version " " VER\fR
.br
Set Ice version on imported servers.

.SH SEE ALSO

.BR icegridadmin (1),
.BR icegridnode (1),
.BR icegridregistry (1)
