.TH icegriddb 1

.SH NAME

icegriddb - The IceGrid database import/export utility.

.SH SYNOPSIS

icegriddb [options]

.SH DESCRIPTION

The icegriddb utility is a command-line tool for importing and exporting IceGrid
databases. Full documentation for icegriddb is available
online at:
.br
https://doc.zeroc.com/display/Ice37/IceGrid+Database+Utility

.SH OPTIONS

.TP
.BR \-h ", " \-\-help\fR
.br
Show program help.

.TP
.BR \-v ", " \-\-version\fR
.br
Display the Ice version.

.TP
.BR \-\-import " " FILE\fR
.br
Import database from the specifed file.

.TP
.BR \-\-export " " FILE\fR
.br
Export database to the specified file.

.TP
.BR \-\-dbpath " " DIR\fR
.br
Source or target database environment.

.TP
.BR \-\-mapsize " " VALUE\fR
.br
Set LMDB map size in MB (optional, import only).

.TP
.BR \-\-server\-version " " VER\fR
.br
Set Ice version for IceGrid servers (optional, import only).

.TP
.BR \-d ", " \-\-debug\fR
.br
Print debug messages.

.SH SEE ALSO

.BR icegridadmin (1),
.BR icegridnode (1),
.BR icegridregistry (1)
