.mso www.tmac

.TH icepatch2client 1

.SH NAME

icepatch2client - The IcePatch2 client.

.SH SYNOPSIS

icepatch2client --IcePatch2Client.Proxy="IcePatch2Server/server:tcp -h somehost.com -p 10000"

.SH DESCRIPTION

The IcePatch2 client. Full documentation for icepatch2client is available
online at:
.br
https://doc.zeroc.com/ice/3.6/ice-services/icepatch2/running-the-icepatch2-client

.SH OPTIONS

.TP
.BR \-h ", " \-\-help\fR
.br
Displays help message.

.TP
.BR \-v ", " \-\-version\fR
Displays the Ice version.

.TP
.BR \-t ", " \-\-thorough\fR
.br
Do a thorough patch, recomputing all checksums.

.SH SEE ALSO

.BR icepatch2calc (1),
.BR icepatch2server (1)
