.TH icepatch2server 1

.SH NAME

icepatch2server - The IcePatch2 server.

.SH SYNOPSIS

icepatch2server <data directory>

.SH DESCRIPTION

The IcePatch2 server. Full documentation for icepatch2server is available
online at:
.br
https://doc.zeroc.com/display/Ice37/Running+the+IcePatch2+Server

.SH OPTIONS

.TP
.BR \-h ", " \-\-help\fR
.br
Displays a help message.

.TP
.BR \-v ", " \-\-version\fR
Displays the Ice version.

.TP
.BR \-\-daemon\fR
.br
Run as a daemon.

.TP
.BR \-\-pidfile " " FILE
.br
Write process ID into FILE.

.TP
.BR \-\-noclose\fR
.br
Do not close open file descriptors.

.TP
.BR \-\-nochdir\fR
.br
Do not change the current working directory.

.SH SEE ALSO

.BR icepatch2calc (1),
.BR icepatch2client (1)
