.TH icestormdb 1

.SH NAME

icestormdb - The IceStorm database import/export utility.

.SH SYNOPSIS

icestormdb [options]

.SH DESCRIPTION

The icestormdb utility is a command-line tool for importing and exporting IceStorm
databases. Full documentation for icestormdb is available
online at:
.br
https://doc.zeroc.com/display/Ice37/icestormdb+Command+Line+Tool

.SH OPTIONS

.TP
.BR \-h ", " \-\-help\fR
.br
Show program help.

.TP
.BR \-v ", " \-\-version\fR
.br
Display the Ice version.

.TP
.BR \-d ", " \-\-debug\fR
.br
Print debug messages.

.TP
.BR \-\-import " " FILE\fR
.br
Import database from specifed file.

.TP
.BR \-\-export " " FILE\fR
.br
Export database to specified file.

.TP
.BR \-\-dbhome " " DIR\fR
.br
The database directory.

.SH SEE ALSO

.BR icestormadmin (1)
