.mso www.tmac

.TH icestormadmin 1

.SH NAME

icestormadmin - The IceStorm administration tool.

.SH SYNOPSIS

icestormadmin [options] [file...]

.SH DESCRIPTION

The IceStorm administration tool is a command-line program that provides
administrative control of an IceStorm server. Full documentation for
icestormadmin is available online at:
.br
https://doc.zeroc.com/display/Ice37/IceStorm+Administration

.SH OPTIONS

.TP
.BR \-h ", " \-\-help\fR
.br
Displays a help message.

.TP
.BR \-v ", " \-\-version\fR
Displays the Ice version.

.TP
.BR \-e " " COMMANDS\fR
.br
Execute COMMANDS.

.TP
.BR \-d ", " \-\-debug\fR
.br
Print debug messages.

.SH SEE ALSO

.BR icestormdb (1)
