.TH icestormmigrate 1

.SH NAME

icestormmigrate - Utility for migration of IceStorm database.

.SH SYNOPSIS

icestormmigrate <path-to-recovered.db> db

.SH DESCRIPTION

The icestormmigrate utility upgrades a 3.1 or 3.2 IceStorm database
environment to a 3.3 or superior IceStorm database environment.
For details about icestormmigrate consult:
.br
https://doc.zeroc.com/ice/3.6/ice-release-notes/upgrading-your-application-from-ice-3-2-or-earlier-releases

.SH SEE ALSO

.BR icestormadmin (1)
