.TH icestormdb 1

.SH NAME

icestormdb - The IceStorm database import/export utility.

.SH SYNOPSIS

icestormdb [options]

.SH DESCRIPTION

The icestormdb utility is a command-line tool for importing and exporting IceStorm
databases. Full documentation for icestormdb is available
online at:
.br
https://doc.zeroc.com/ice/3.7/ice-services/icestorm/icestorm-database-utility

.SH OPTIONS

.TP
.BR \-h ", " \-\-help\fR
.br
Show program help.

.TP
.BR \-v ", " \-\-version\fR
.br
Display the Ice version.

.TP
.BR \-v ", " \-\-version\fR
.br
Display the Ice version.

.TP
.BR \-\-import " " FILE\fR
.br
Import database from the specifed file.

.TP
.BR \-\-export " " FILE\fR
.br
Export database to the specified file.

.TP
.BR \-\-dbpath " " DIR\fR
.br
Source or target database environment.

.TP
.BR \-\-mapsize " " VALUE\fR
.br
Set LMDB map size in MB (optional, import only).

.TP
.BR \-d ", " \-\-debug\fR
.br
Print debug messages.

.SH SEE ALSO

.BR icestormadmin (1)
