// **********************************************************************
//
// Copyright (c) 2003-2014 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

#ifndef __PING_IDL__
#define __PING_IDL__

module Test
{

typedef sequence<octet> ByteSeq;
const long ByteSeqSize = 500000;

typedef sequence<string> StringSeq;
const long StringSeqSize = 50000;

struct StringDouble
{
  string str;
  double d;
};

typedef sequence<StringDouble> StringDoubleSeq;
const long StringDoubleSeqSize = 50000;

struct FixedStruct
{
    long i;
    long j;
    double d;
};
typedef sequence<FixedStruct> FixedSeq;
const long FixedSeqSize = 50000;

interface Throughput
{
    void sendByteSeq(in ByteSeq seq);
    void sendStringSeq(in StringSeq seq);
    void sendStringDoubleSeq(in StringDoubleSeq seq);

    void ping();
    oneway void ping_oneway();

    void shutdown();
};

};

#endif  // __PING_IDL__
