// **********************************************************************
//
// Copyright (c) 2003-2005 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Generated by makeprops.py from file `../config/PropertyNames.def', Thu Apr 13 13:32:39 2006

// IMPORTANT: Do not edit this file -- any edits made here will be lost!

#ifndef ICE_INTERNAL_PropertyNames_H
#define ICE_INTERNAL_PropertyNames_H

#include <Ice/Config.h>
namespace IceInternal
{

class PropertyNames
{
public:

    static const char* IceProps[];
    static const char* IceBoxProps[];
    static const char* IceGridProps[];
    static const char* IcePatch2Props[];
    static const char* IceSSLProps[];
    static const char* IceStormProps[];
    static const char* Glacier2Props[];
    static const char* FreezeProps[];

    static const char* const* validProps[];
    static const char* clPropNames[];
};

}

#endif
