// Copyright (c) ZeroC, Inc. All rights reserved.

// Generated by makeprops.py from file ./config/PropertyNames.xml, Thu May  9 15:01:37 2024

// IMPORTANT: Do not edit this file -- any edits made here will be lost!

#ifndef ICE_INTERNAL_PropertyNames_H
#define ICE_INTERNAL_PropertyNames_H

#include <string>

namespace IceInternal
{

    struct Property
    {
        const char* pattern;
        bool usesRegex;
        const char* defaultValue;
        bool deprecated;
        const char* deprecatedBy;

        Property(const char* n, bool r, const char* dv, bool d, const char* b)
            : pattern(n),
              usesRegex(r),
              defaultValue(dv),
              deprecated(d),
              deprecatedBy(b)
        {
        }

        Property() = delete;
    };

    struct PropertyArray
    {
        const Property* properties;
        const int length;

        PropertyArray(const Property* p, size_t len) : properties(p), length(static_cast<int>(len)) {}
    };

    class PropertyNames
    {
    public:
        static const PropertyArray IceProps;
        static const PropertyArray IceMXProps;
        static const PropertyArray IceDiscoveryProps;
        static const PropertyArray IceLocatorDiscoveryProps;
        static const PropertyArray IceBoxProps;
        static const PropertyArray IceBoxAdminProps;
        static const PropertyArray IceBridgeProps;
        static const PropertyArray IceGridAdminProps;
        static const PropertyArray IceGridProps;
        static const PropertyArray IceSSLProps;
        static const PropertyArray IceStormAdminProps;
        static const PropertyArray IceBTProps;
        static const PropertyArray Glacier2Props;
        static const PropertyArray Glacier2CryptPermissionsVerifierProps;

        static const PropertyArray validProps[];
        static const char* clPropNames[];
    };

}

#endif
