name: Setup .NET

inputs:
  include_net10:
    description: "Include .NET 10"
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Setup .NET 10
      if: inputs.include_net10 == 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x
