name: "Build IceGrid GUI JAR"

on:
  workflow_call:
    inputs:
      ice_version:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      ice_version:
        description: "The Ice version to build"
        required: false

jobs:
  build-icegridgui-jar:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup C++
        uses: ./.github/actions/setup-cpp

      - name: Setup Java
        uses: ./.github/actions/setup-java

      - name: Build IceGrid GUI
        run: |
          nuget restore ..\cpp\msbuild\ice.sln
          MSBuild ..\cpp\msbuild\ice.sln /t:"c++98\slice2java" /p:Configuration=Release /p:Platform=x64
          ./gradlew.bat dist -PcppPlatform=x64 -PcppConfiguration=Release
        working-directory: java

      - name: Upload IceGrid GUI JAR
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: icegridgui-jar
          path: |
            java/lib/icegridgui.jar
