name: "Build RPM Packages"

on:
  workflow_dispatch:
    inputs:
      ice_version:
        description: "The Ice version to build"
        required: false
  workflow_call:
    inputs:
      ice_version:
        required: false
        type: string

jobs:
  build:
    name: "Build for ${{ matrix.distribution }}-${{ matrix.arch }}"
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      matrix:
        distribution: [el9, el10, amzn2023]
        arch: [x86_64, aarch64]

    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: ice

      - name: Load version info
        run: |
          source ice/config/version.env
          echo "CHANNEL=$CHANNEL" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Log in to GHCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: zeroc-ice
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build RPM packages
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/workspace" \
            -e ICE_VERSION="${{ inputs.ice_version }}" \
            -e GIT_TAG="${{ github.ref_name }}" \
            ghcr.io/zeroc-ice/ice-rpm-builder-${{ matrix.distribution }}:${CHANNEL} \
            /workspace/ice/packaging/rpm/build-package.sh

      - name: Sign RPM packages
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/workspace" \
            -e GPG_KEY="${{ secrets.ICE_3_7_CI_SIGNER_KEY }}" \
            -e GPG_KEY_ID="${{ secrets.ICE_3_7_CI_SIGNER_KEY_ID }}" \
            ghcr.io/zeroc-ice/ice-rpm-builder-${{ matrix.distribution }}:${CHANNEL} \
            /workspace/ice/packaging/rpm/sign-package.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: rpm-packages-${{ matrix.distribution }}-${{ matrix.arch }}
          path: |
            build/RPMS/*
            build/SRPMS/*
