name: "Build Brew Packages"

on:
  workflow_call:
    inputs:
      ice_version:
        required: true
        type: string
      channel:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      ice_version:
        description: "The Ice version number to use"
        required: true
      channel:
        description: "The channel to publish to (e.g., 3.8, nightly)"
        required: true

permissions:
  contents: write

jobs:
  build-xcfranework-packages:
    runs-on: macos-26

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup C++
        uses: ./.github/actions/setup-cpp

      - name: Setup Cache
        uses: ./.github/actions/setup-cache
        with:
          prefix: build-xcframework-packages

      - name: Build XCFramework Packages
        run: make OPTIMIZE=yes PLATFORMS="all" CONFIGS="static" srcs
        working-directory: cpp

      - name: Create XCFrameworks Zip archives
        run: |
          for dir in *.xcframework; do
            framework_name=$(basename $dir)
            framework_zip=${framework_name/.xcframework/-${{inputs.ice_version}}.xcframework.zip}
            zip -r $framework_zip $dir
          done
        working-directory: cpp/lib/XCFrameworks

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xcframework-packages
          path: cpp/lib/XCFrameworks/*.zip

  build-brew-packages:
    runs-on: macos-26
    # Stable brew release must be build manually.
    if: ${{ inputs.channel == 'nightly' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup C++
        uses: ./.github/actions/setup-cpp

      - name: Setup Cache
        uses: ./.github/actions/setup-cache
        with:
          prefix: build-brew-packages

      - name: Update and Push Nightly Tap
        run: |
          ./packaging/brew/update-nightly-tap.sh "${{ inputs.ice_version }}" "https://download.zeroc.com/ice/nightly"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: homebrew-bottle
          path: |
            ./*.tar.gz
            ./*.patch
