name: "Build Swift Packages"

on:
  workflow_call:
    inputs:
      ice_version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      ice_version:
        description: "The Ice version to build"
        required: true

jobs:
  build-swift-packages:
    name: "Build Swift Packages"
    runs-on: macos-15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup C++
        uses: ./.github/actions/setup-cpp

      - name: Build SPM sources
        run: ./build-spm-sources.py
        working-directory: packaging/swift

      - name: Create SPM sources archive
        run: tar -czvf spm-sources-${{ inputs.ice_version }}.tar.gz -C packaging/swift spm

      - name: Upload SPM sources artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: spm-sources
          path: spm-sources-${{ inputs.ice_version }}.tar.gz
