name: "Build Brew Packages"

on:
  workflow_call:
    inputs:
      ice_version:
        required: true
        type: string
      channel:
        required: true
        type: string
      quality:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      ice_version:
        description: "The Ice version number to use"
        required: true
      channel:
        description: "The release channel (e.g., 3.9, 3.8)"
        required: true
      quality:
        description: "Release quality (e.g., stable, nightly, RC)"
        required: true
        default: "nightly"

permissions:
  contents: write

jobs:
  build-brew-packages:
    runs-on: macos-26
    # Stable brew release must be build manually.
    if: ${{ inputs.quality == 'nightly' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup C++
        uses: ./.github/actions/setup-cpp

      - name: Update Nightly Tap
        run: |
          ./packaging/brew/update-nightly-tap.sh "${{ inputs.channel }}" "${{ inputs.quality }}" "${{ inputs.ice_version }}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: homebrew-bottle
          path: |
            ./*.tar.gz
            ./*.patch
