name: "Build Ice Repo DEB Packages"

on:
  workflow_dispatch:
    inputs:
      quality:
        description: "Release quality (e.g., stable, nightly, RC)"
        required: false
        default: "nightly"

jobs:
  build:
    name: "Build Ice Repo DEB packages for ${{ matrix.distribution }}"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        distribution: [debian12, debian13, ubuntu24.04, ubuntu26.04]

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: ice

      - name: Load version info
        run: |
          source ice/config/version.env
          echo "CHANNEL=$CHANNEL" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Log in to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: zeroc-ice
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build DEB packages
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/workspace" \
            -e GPG_KEY="${{ secrets.ICE_3_8_CI_SIGNER_KEY }}" \
            -e GPG_KEY_ID="${{ secrets.ICE_3_8_CI_SIGNER_KEY_ID }}" \
            ghcr.io/zeroc-ice/ice-deb-builder-${{ matrix.distribution }}:${CHANNEL} \
            /workspace/ice/packaging/deb/build-repo-package.sh \
            --distribution "${{ matrix.distribution }}" \
            --channel "${CHANNEL}" \
            --quality "${{ inputs.quality }}"

      - name: Sync DEB packages to S3
        run: |
          if [ "${QUALITY}" = "stable" ]; then
            UPLOAD_PATH="ice/${CHANNEL}/${DISTRIBUTION}"
          else
            UPLOAD_PATH="ice/${QUALITY}/${CHANNEL}/${DISTRIBUTION}"
          fi

          aws s3 cp build/*.deb "s3://${S3_DOWNLOADS_BUCKET}/${UPLOAD_PATH}/"
        env:
          QUALITY: ${{ inputs.quality }}
          DISTRIBUTION: ${{ matrix.distribution }}
          S3_DOWNLOADS_BUCKET: ${{ vars.S3_DOWNLOADS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: deb-packages-${{ matrix.distribution }}
          path: |
            build/*.deb
