name: "Build XCFramework Packages"

on:
  workflow_call:
    inputs:
      ice_version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      ice_version:
        description: "The Ice version number to use"
        required: true

permissions:
  contents: write

jobs:
  build-xcframework-packages:
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup C++
        uses: ./.github/actions/setup-cpp

      - name: Build XCFramework Packages
        run: make OPTIMIZE=yes
        working-directory: packaging/swift

      - name: Set Version (For Nightly Builds)
        run: |
          echo "ICE_VERSION=${{inputs.ice_version}}" >> $GITHUB_ENV
        if: ${{ inputs.ice_version != '' }}

      - name: Set Version (For Release Builds)
        run: |
          source config/version.env
          echo "ICE_VERSION=${VERSION}" >> $GITHUB_ENV
        if: ${{ inputs.ice_version == '' }}

      - name: Create XCFrameworks Zip archives
        run: |
          for dir in *.xcframework; do
            framework_name=$(basename $dir)
            framework_zip=${framework_name/.xcframework/-${ICE_VERSION}.xcframework.zip}
            zip -r $framework_zip $dir
          done
        working-directory: packaging/swift/build/XCFrameworks

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xcframework-packages
          path: packaging/swift/build/XCFrameworks/*.zip
