name: "Build Ice Repo DEB Packages"

on:
  workflow_dispatch:
    inputs:
      quality:
        description: "Release quality (e.g., stable, nightly, RC)"
        required: false
        default: "nightly"

jobs:
  build:
    name: "Build Ice Repo DEB packages for ${{ matrix.distribution }}"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        distribution: [debian12, debian13, ubuntu24.04, ubuntu26.04]

    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: ice

      - name: Load version info
        run: |
          source ice/config/version.env
          echo "CHANNEL=$CHANNEL" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Log in to GHCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: zeroc-ice
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build DEB packages
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/workspace" \
            -e GPG_KEY="${{ secrets.ICE_3_8_CI_SIGNER_KEY }}" \
            -e GPG_KEY_ID="${{ secrets.ICE_3_8_CI_SIGNER_KEY_ID }}" \
            ghcr.io/zeroc-ice/ice-deb-builder-${{ matrix.distribution }}:${CHANNEL} \
            /workspace/ice/packaging/deb/build-repo-package.sh \
            --distribution "${{ matrix.distribution }}" \
            --channel "${CHANNEL}" \
            --quality "${{ inputs.quality }}"

      - name: Sync DEB packages to S3
        run: |
          if [ "${QUALITY}" = "stable" ]; then
            UPLOAD_PATH="ice/${CHANNEL}/${DISTRIBUTION}"
          else
            UPLOAD_PATH="ice/${QUALITY}/${CHANNEL}/${DISTRIBUTION}"
          fi

          aws s3 cp build/*.deb "s3://zeroc-downloads/${UPLOAD_PATH}/"
        env:
          QUALITY: ${{ inputs.quality }}
          DISTRIBUTION: ${{ matrix.distribution }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: deb-packages-${{ matrix.distribution }}
          path: |
            build/*.deb
