name: Java

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

jobs:
  checkstyle:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup C++
        uses: ./.github/actions/setup-cpp

      - name: Setup Java
        uses: ./.github/actions/setup-java

      - name: Build slice2java
        run: make -C cpp slice2java

      - name: Run checkstyle formatter
        working-directory: java
        run: ./gradlew check

  rewrite:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup C++
        uses: ./.github/actions/setup-cpp

      - name: Setup Java
        uses: ./.github/actions/setup-java

      - name: Build slice2java
        run: make -C cpp slice2java

      - name: Run rewrite linter
        working-directory: java
        run: ./gradlew rewriteDryRun --no-parallel --no-configuration-cache
