name: Check Links

on:
  workflow_dispatch:
  push:
    branches: ["3.7"]
    paths:
      - "**.md"
      - "**.html"
      - ".github/workflows/links.yml"
  pull_request:
    branches: ["3.7"]
    paths:
      - "**.md"
      - "**.html"
      - ".github/workflows/links.yml"

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Check links
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: >-
            --config .lychee.toml
            --verbose
            --no-progress
            '**/*.md'
            '**/*.html'
          fail: true
