<?php
//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `ServantLocatorF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


namespace Ice
{
    global $Ice__t_ServantLocator;
    if(!isset($Ice__t_ServantLocator))
    {
        $Ice__t_ServantLocator = IcePHP_declareClass('::Ice::ServantLocator');
    }
}
?>
